'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useParams, useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import SafeRichText from '@/components/SafeRichText'
import styles from '../portal.module.css'

type Mode = 'full' | 'renewal' | 'summer_short' | 'permission_only' | 'short_youth' | 'adult_short'
type Consent = { id:number; title:string; body:string; required:boolean; applies_to_modes:Mode[]; display_order:number }
type Program = { public_id:string; name:string; program_type:string; audience:string; season_label:string|null; description:string|null; registration_intro:string|null; location:string|null; starts_on:string|null; ends_on:string|null; meeting_days:string[]; capacity:number|null; active_count:number; registration_modes:Mode[]; consents:Consent[] }
type Guardian = { name:string; relationship:string; email:string; phone:string; other_phone:string; address:string; preferred_contact:string }
type Emergency = { name:string; relationship:string; phone:string }
type ChildForm = { key:string; existing_child_id?:number; selected:boolean; first_name:string; last_name:string; birth_date:string; school:string; grade:string; attendance_days:string[]; attends_other_program:boolean; other_program_arrival_notes:string; dismissal_plan:string; dismissal_notes:string; allergies:string; medical_conditions:string; learning_support:string; behavioral_support:string; actions_to_take:string; important_care_notes:string; shirt_size:string; food_restrictions:string; program_notes:string }
type RenewalContext = { household_id:number; household_display_name:string; guardian:Partial<Guardian>; children:Array<Partial<ChildForm> & { existing_child_id:number; emergency?:Emergency|null }>; expires_at:string }
type AdultForm = { first_name:string; last_name:string; email:string; phone:string; other_phone:string; address:string; preferred_contact:string; emergency_contact_name:string; emergency_contact_relationship:string; emergency_contact_phone:string }

const modeCopy:Record<Mode,{title:string;description:string}> = {
  full:{title:'New family registration',description:'Complete the full registration for children who are new to Juanita Hub.'},
  renewal:{title:'Returning family renewal',description:'Review existing family information and renew one or more children.'},
  summer_short:{title:'Returning family summer form',description:'Confirm your family information and answer the shorter summer-specific questions.'},
  permission_only:{title:'Permission form',description:'Give permission for an existing child to participate in this program.'},
  short_youth:{title:'Short youth registration',description:'A shorter registration for a child joining a club or community activity.'},
  adult_short:{title:'Adult registration',description:'Register yourself for an adult class or workshop.'},
}
const returningModes:Mode[]=['renewal','summer_short','permission_only']
const days=['Monday','Tuesday','Wednesday','Thursday','Friday']
function blankGuardian():Guardian{return{name:'',relationship:'Parent/Guardian',email:'',phone:'',other_phone:'',address:'',preferred_contact:'Text'}}
function blankEmergency():Emergency{return{name:'',relationship:'',phone:''}}
function blankAdult():AdultForm{return{first_name:'',last_name:'',email:'',phone:'',other_phone:'',address:'',preferred_contact:'Text',emergency_contact_name:'',emergency_contact_relationship:'',emergency_contact_phone:''}}
function blankChild():ChildForm{return{key:crypto.randomUUID(),selected:true,first_name:'',last_name:'',birth_date:'',school:'',grade:'',attendance_days:[],attends_other_program:false,other_program_arrival_notes:'',dismissal_plan:'',dismissal_notes:'',allergies:'',medical_conditions:'',learning_support:'',behavioral_support:'',actions_to_take:'',important_care_notes:'',shirt_size:'',food_restrictions:'',program_notes:''}}
function toChild(source:Partial<ChildForm> & {existing_child_id?:number}):ChildForm{return{...blankChild(),...source,key:`existing-${source.existing_child_id ?? crypto.randomUUID()}`,selected:true,attendance_days:source.attendance_days ?? []}}

export default function ProgramRegistrationPage(){
  const params=useParams<{publicId:string}>(); const search=useSearchParams(); const publicId=params.publicId; const token=search.get('token') ?? ''
  const [program,setProgram]=useState<Program|null>(null); const [context,setContext]=useState<RenewalContext|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const [mode,setMode]=useState<Mode|null>(null); const [guardian,setGuardian]=useState<Guardian>(blankGuardian()); const [emergency,setEmergency]=useState<Emergency>(blankEmergency()); const [children,setChildren]=useState<ChildForm[]>([blankChild()]); const [adult,setAdult]=useState<AdultForm>(blankAdult())
  const [consents,setConsents]=useState<Record<number,boolean | undefined>>({}); const [signature,setSignature]=useState(''); const [signatureDate,setSignatureDate]=useState(new Date().toISOString().slice(0,10)); const [saving,setSaving]=useState(false); const [successCode,setSuccessCode]=useState('')

  useEffect(()=>{let mounted=true; async function load(){setLoading(true); const {data,error:programError}=await supabase.rpc('public_registration_program',{p_public_id:publicId}); if(!mounted)return; if(programError||!data){setError(programError?.message ?? 'This registration is not currently available.');setLoading(false);return} const loaded=data as Program; setProgram(loaded)
    let renewal:RenewalContext|null=null; if(token){const result=await supabase.rpc('public_registration_renewal_context',{p_public_id:publicId,p_token:token}); if(result.data) renewal=result.data as RenewalContext; if(result.error) setError(result.error.message)}
    if(!mounted)return; setContext(renewal); if(renewal){setGuardian({...blankGuardian(),...renewal.guardian});setChildren(renewal.children.map(c=>toChild(c)));const em=renewal.children.find(c=>c.emergency)?.emergency;if(em)setEmergency({...blankEmergency(),...em});const preferred=loaded.registration_modes.find(m=>returningModes.includes(m));setMode(preferred ?? loaded.registration_modes[0] ?? null)} else {const preferred=loaded.registration_modes.find(m=>!returningModes.includes(m));setMode(preferred ?? loaded.registration_modes[0] ?? null)} setLoading(false)} void load(); return()=>{mounted=false}},[publicId,token])

  const visibleModes=useMemo(()=>program?.registration_modes ?? [],[program]); const activeConsents=useMemo(()=>program?.consents.filter(c=>mode && c.applies_to_modes.includes(mode)) ?? [],[program,mode]);
  const requiresToken=mode ? returningModes.includes(mode):false; const selectedChildren=children.filter(c=>c.selected)
  function updateChild(key:string,patch:Partial<ChildForm>){setChildren(current=>current.map(c=>c.key===key?{...c,...patch}:c))}
  function toggleDay(key:string,day:string){setChildren(current=>current.map(c=>c.key!==key?c:{...c,attendance_days:c.attendance_days.includes(day)?c.attendance_days.filter(d=>d!==day):[...c.attendance_days,day]}))}

  async function submit(){if(!program||!mode||saving)return; setError(''); if(requiresToken&&!context){setError('Please use the private returning-family link sent by the center.');return} if(mode!=='adult_short'&&selectedChildren.length===0){setError('Select or add at least one child.');return} if(!signature.trim()){setError('Please type the name of the person signing this registration.');return} const missing=activeConsents.find(c=>c.required&&consents[c.id]!==true); if(missing){setError(`Please accept the required acknowledgment: ${missing.title}`);return} const unanswered=activeConsents.find(c=>!c.required&&typeof consents[c.id] !== 'boolean'); if(unanswered){setError(`Please choose an answer for: ${unanswered.title}`);return}
    setSaving(true); const payload={guardian,emergency,adult,children:selectedChildren,signature_name:signature.trim(),signature_date:signatureDate,consents:activeConsents.map(c=>({id:c.id,agreed:Boolean(consents[c.id])}))}; const {data,error:submitError}=await supabase.rpc('submit_public_registration',{p_public_id:publicId,p_mode:mode,p_payload:payload,p_token:token||null}); if(submitError)setError(submitError.message); else setSuccessCode(data?.submission_code ?? 'SUBMITTED'); setSaving(false)
  }

  if(loading)return <main className={styles.portalShell}><div className={styles.stateCard}>Loading registration…</div></main>
  if(!program)return <main className={styles.portalShell}><div className={styles.registrationWrap}><Link className={styles.backLink} href="/register">← Registration home</Link><div className={styles.errorCard}>{error||'Registration unavailable.'}</div></div></main>
  if(successCode)return <main className={styles.portalShell}><div className={styles.registrationWrap}><div className={styles.successCard}><div className={styles.successIcon}>✓</div><h1>Registration submitted</h1><p>Your information was sent securely to the center for review. Keep this confirmation code for your records.</p><div className={styles.confirmationCode}>{successCode}</div><br/><Link className={styles.primaryLink} href="/register">Back to programs</Link></div></div></main>

  const simplePermission=mode==='permission_only'; const summer=mode==='summer_short'; const shortYouth=mode==='short_youth';
  return <main className={styles.portalShell}><div className={styles.registrationWrap}>
    <Link className={styles.backLink} href="/register">← All programs</Link>
    <section className={styles.registrationHero}><span className={styles.eyebrow}>{program.program_type.replace('_',' ')}</span><h1>{program.name}</h1><SafeRichText className={styles.richText} text={program.registration_intro||program.description||'Complete the form below to register.'} /></section>
    {token&&context&&<div className={styles.tokenNotice}>Returning household found: <strong>{context.household_display_name}</strong>. Review the information below and update anything that changed.</div>}
    {token&&!context&&<div className={styles.warningNotice}>This returning-family link could not be verified. It may have expired or already been used.</div>}
    {visibleModes.length>1&&<div className={styles.modeGrid}>{visibleModes.map(m=><button key={m} type="button" className={`${styles.modeCard} ${mode===m?styles.modeCardActive:''}`} onClick={()=>setMode(m)}><strong>{modeCopy[m].title}</strong><span>{modeCopy[m].description}</span></button>)}</div>}
    {mode&&requiresToken&&!context?<section className={styles.formCard}><h2>Returning family access</h2><p>This registration path protects existing family information. Please open the private renewal/permission link provided by the center. If you need a new link, contact center staff.</p></section>:<>
      {mode==='adult_short'?<section className={styles.formCard}><h2>Your information</h2><div className={styles.formGrid}>{(['first_name','last_name','email','phone','other_phone','address'] as const).map(field=><label className={`${styles.field} ${field==='address'?styles.fieldFull:''}`} key={field}><span>{field.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}{field==='first_name'?' *':''}</span><input value={adult[field]} onChange={e=>setAdult(a=>({...a,[field]:e.target.value}))}/></label>)}<label className={styles.field}><span>Preferred contact</span><select value={adult.preferred_contact} onChange={e=>setAdult(a=>({...a,preferred_contact:e.target.value}))}><option>Text</option><option>Phone</option><option>Email</option></select></label></div><div className={styles.sectionDivider}/><h2>Emergency contact</h2><div className={styles.formGrid}><label className={styles.field}><span>Name</span><input value={adult.emergency_contact_name} onChange={e=>setAdult(a=>({...a,emergency_contact_name:e.target.value}))}/></label><label className={styles.field}><span>Relationship</span><input value={adult.emergency_contact_relationship} onChange={e=>setAdult(a=>({...a,emergency_contact_relationship:e.target.value}))}/></label><label className={styles.field}><span>Phone</span><input value={adult.emergency_contact_phone} onChange={e=>setAdult(a=>({...a,emergency_contact_phone:e.target.value}))}/></label></div></section>:<>
        <section className={styles.formCard}><h2>Parent / guardian</h2><p>Shared family information only needs to be entered once for this submission.</p><div className={styles.formGrid}><label className={styles.field}><span>Full name *</span><input value={guardian.name} onChange={e=>setGuardian(g=>({...g,name:e.target.value}))}/></label><label className={styles.field}><span>Relationship</span><input value={guardian.relationship} onChange={e=>setGuardian(g=>({...g,relationship:e.target.value}))}/></label><label className={styles.field}><span>Email</span><input type="email" value={guardian.email} onChange={e=>setGuardian(g=>({...g,email:e.target.value}))}/></label><label className={styles.field}><span>Phone</span><input type="tel" value={guardian.phone} onChange={e=>setGuardian(g=>({...g,phone:e.target.value}))}/></label><label className={styles.field}><span>Other phone</span><input type="tel" value={guardian.other_phone} onChange={e=>setGuardian(g=>({...g,other_phone:e.target.value}))}/></label><label className={styles.field}><span>Preferred contact</span><select value={guardian.preferred_contact} onChange={e=>setGuardian(g=>({...g,preferred_contact:e.target.value}))}><option>Text</option><option>Phone</option><option>Email</option></select></label><label className={`${styles.field} ${styles.fieldFull}`}><span>Address</span><input value={guardian.address} onChange={e=>setGuardian(g=>({...g,address:e.target.value}))}/></label></div></section>
        {!simplePermission&&<section className={styles.formCard}><h2>Emergency contact</h2><p>Please list someone other than the primary parent/guardian when possible.</p><div className={styles.formGrid}><label className={styles.field}><span>Full name</span><input value={emergency.name} onChange={e=>setEmergency(x=>({...x,name:e.target.value}))}/></label><label className={styles.field}><span>Relationship</span><input value={emergency.relationship} onChange={e=>setEmergency(x=>({...x,relationship:e.target.value}))}/></label><label className={styles.field}><span>Phone</span><input value={emergency.phone} onChange={e=>setEmergency(x=>({...x,phone:e.target.value}))}/></label></div></section>}
        <section className={styles.formCard}><h2>{context?'Children to include':'Child information'}</h2><p>{context?'Choose any or all children in this household. You can update information for each selected child.':'Add each child you are registering for this program.'}</p>{children.map((child,index)=><div className={styles.childCard} key={child.key}><div className={styles.childHeader}><h3>{child.first_name||`Child ${index+1}`}</h3>{context?<label className={styles.checkRow}><input type="checkbox" checked={child.selected} onChange={e=>updateChild(child.key,{selected:e.target.checked})}/><span>Include</span></label>:children.length>1?<button type="button" className={styles.dangerButton} onClick={()=>setChildren(c=>c.filter(x=>x.key!==child.key))}>Remove</button>:null}</div>{child.selected&&<div className={styles.formGrid}>
          <label className={styles.field}><span>First name *</span><input value={child.first_name} disabled={Boolean(child.existing_child_id)} onChange={e=>updateChild(child.key,{first_name:e.target.value})}/></label><label className={styles.field}><span>Last name</span><input value={child.last_name} disabled={Boolean(child.existing_child_id)} onChange={e=>updateChild(child.key,{last_name:e.target.value})}/></label>
          {!simplePermission&&<><label className={styles.field}><span>Date of birth</span><input type="date" value={child.birth_date||''} onChange={e=>updateChild(child.key,{birth_date:e.target.value})}/></label>{!summer&&<><label className={styles.field}><span>School</span><input value={child.school||''} onChange={e=>updateChild(child.key,{school:e.target.value})}/></label><label className={styles.field}><span>Grade</span><input value={child.grade||''} onChange={e=>updateChild(child.key,{grade:e.target.value})}/></label></>}
          <div className={`${styles.field} ${styles.fieldFull}`}><span>Planned attendance days</span><div className={styles.dayGrid}>{days.map(day=><label className={styles.dayCheck} key={day}><input type="checkbox" checked={child.attendance_days.includes(day)} onChange={()=>toggleDay(child.key,day)}/>{day.slice(0,3)}</label>)}</div></div>
          <label className={`${styles.checkRow} ${styles.fieldFull}`}><input type="checkbox" checked={child.attends_other_program} onChange={e=>updateChild(child.key,{attends_other_program:e.target.checked})}/><span>{summer?'My child has another summer commitment/program.':'My child attends another afterschool program/activity.'}</span></label>{child.attends_other_program&&<label className={`${styles.field} ${styles.fieldFull}`}><span>Other commitment / expected arrival details</span><textarea value={child.other_program_arrival_notes} onChange={e=>updateChild(child.key,{other_program_arrival_notes:e.target.value})}/></label>}
          {summer&&<><label className={styles.field}><span>Shirt size</span><input value={child.shirt_size} onChange={e=>updateChild(child.key,{shirt_size:e.target.value})}/></label><label className={styles.field}><span>Food allergies / dietary restrictions</span><input value={child.food_restrictions} onChange={e=>updateChild(child.key,{food_restrictions:e.target.value})}/></label></>}
          {!shortYouth&&!summer&&<><label className={styles.field}><span>Dismissal plan</span><input value={child.dismissal_plan} onChange={e=>updateChild(child.key,{dismissal_plan:e.target.value})}/></label><label className={styles.field}><span>Dismissal notes</span><input value={child.dismissal_notes} onChange={e=>updateChild(child.key,{dismissal_notes:e.target.value})}/></label></>}
          <label className={`${styles.field} ${styles.fieldFull}`}><span>Allergies</span><textarea value={child.allergies} onChange={e=>updateChild(child.key,{allergies:e.target.value})}/></label><label className={`${styles.field} ${styles.fieldFull}`}><span>Medical conditions / health concerns</span><textarea value={child.medical_conditions} onChange={e=>updateChild(child.key,{medical_conditions:e.target.value})}/></label>{!summer&&<><label className={`${styles.field} ${styles.fieldFull}`}><span>Learning support / IEP information</span><textarea value={child.learning_support} onChange={e=>updateChild(child.key,{learning_support:e.target.value})}/></label><label className={`${styles.field} ${styles.fieldFull}`}><span>Behavioral support information</span><textarea value={child.behavioral_support} onChange={e=>updateChild(child.key,{behavioral_support:e.target.value})}/></label></>}<label className={`${styles.field} ${styles.fieldFull}`}><span>Actions staff should take / important instructions</span><textarea value={child.actions_to_take} onChange={e=>updateChild(child.key,{actions_to_take:e.target.value})}/></label></>}
          </div>}</div>)}{!context&&mode!=='permission_only'&&<button type="button" className={styles.secondaryButton} onClick={()=>setChildren(c=>[...c,blankChild()])}>+ Add another child</button>}</section>
      </>}
      <section className={styles.formCard}><h2>Permissions & signature</h2><p>Review each item before signing. Required acknowledgments must be accepted. Optional permissions still need a clear Yes or No answer.</p>{activeConsents.map(c=><div className={styles.consentCard} key={c.id}><strong>{c.title}{c.required?<span className={styles.required}>Agreement required</span>:<span className={styles.optional}>Choice required</span>}</strong><p>{c.body}</p>{c.required?<label className={styles.checkRow}><input type="checkbox" checked={consents[c.id]===true} onChange={e=>setConsents(x=>({...x,[c.id]:e.target.checked?true:undefined}))}/><span>I agree</span></label>:<div className={styles.consentChoices} role="radiogroup" aria-label={c.title}><label className={styles.consentChoice + (consents[c.id]===true?' '+styles.consentChoiceSelected:'')}><input type="radio" name={'consent-'+c.id} checked={consents[c.id]===true} onChange={()=>setConsents(x=>({...x,[c.id]:true}))}/><span>Yes, I give permission</span></label><label className={styles.consentChoice + (consents[c.id]===false?' '+styles.consentChoiceSelected:'')}><input type="radio" name={'consent-'+c.id} checked={consents[c.id]===false} onChange={()=>setConsents(x=>({...x,[c.id]:false}))}/><span>No, I do not give permission</span></label></div>}</div>)}{activeConsents.length===0&&<div className={styles.smallNote}>No additional program-specific permissions have been configured yet. Your signature confirms that the information in this submission is accurate.</div>}<div className={styles.sectionDivider}/><div className={styles.formGrid}><label className={styles.field}><span>Electronic signature *</span><input value={signature} onChange={e=>setSignature(e.target.value)} placeholder="Type your full name"/></label><label className={styles.field}><span>Date *</span><input type="date" value={signatureDate} onChange={e=>setSignatureDate(e.target.value)}/></label></div></section>
      {error&&<div className={styles.errorCard}>{error}</div>}<div className={styles.actions}><button type="button" className={styles.primaryButton} disabled={saving} onClick={()=>void submit()}>{saving?'Submitting…':'Submit registration'}</button></div>
    </>}
    <footer className={styles.publicFooter}>Juanita Sanders Community Learning Center • Registration powered by Juanita Hub</footer>
  </div></main>
}
