create table if not exists public.program_registration_options (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete cascade,
  registration_mode text not null check (registration_mode in ('full','renewal','summer_short','permission_only','short_youth','adult_short')),
  display_order smallint not null default 0,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  unique (program_id, registration_mode)
);

insert into public.program_registration_options(program_id, registration_mode, display_order, created_by)
select id, registration_mode, 0, created_by
from public.programs
where registration_mode is not null
on conflict (program_id, registration_mode) do nothing;

create index if not exists program_registration_options_created_by_idx
  on public.program_registration_options(created_by);

alter table public.program_registration_options enable row level security;

drop policy if exists "active staff can view program registration options" on public.program_registration_options;
create policy "active staff can view program registration options"
on public.program_registration_options
for select
to authenticated
using ((select current_user_is_active_staff()));

drop policy if exists "admins can insert program registration options" on public.program_registration_options;
create policy "admins can insert program registration options"
on public.program_registration_options
for insert
to authenticated
with check ((select current_user_is_admin()));

drop policy if exists "admins can update program registration options" on public.program_registration_options;
create policy "admins can update program registration options"
on public.program_registration_options
for update
to authenticated
using ((select current_user_is_admin()))
with check ((select current_user_is_admin()));

drop policy if exists "admins can delete program registration options" on public.program_registration_options;
create policy "admins can delete program registration options"
on public.program_registration_options
for delete
to authenticated
using ((select current_user_is_admin()));

grant select, insert, update, delete on table public.program_registration_options to authenticated;
revoke all on table public.program_registration_options from anon;
grant usage, select on sequence public.program_registration_options_id_seq to authenticated;
revoke all on sequence public.program_registration_options_id_seq from anon;;