create table if not exists public.free_prize_wins (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete restrict,
  month_start date not null,
  category_id bigint not null references public.wheel_categories(id) on delete restrict,
  tier_id bigint not null references public.wheel_tiers(id) on delete restrict,
  prize_id bigint references public.wheel_prizes(id) on delete set null,
  prize_name_snapshot text not null,
  category_name_snapshot text not null,
  tier_name_snapshot text not null,
  reason text,
  recorded_by uuid not null references auth.users(id) on delete restrict,
  won_at timestamptz not null default now(),
  constraint free_prize_wins_month_start_first_day check (month_start = date_trunc('month', month_start)::date)
);

create index if not exists free_prize_wins_child_month_idx on public.free_prize_wins(child_id, month_start, won_at desc);
create index if not exists free_prize_wins_month_category_idx on public.free_prize_wins(month_start, category_id, won_at desc);

alter table public.free_prize_wins enable row level security;

drop policy if exists "active staff can read free prize wins" on public.free_prize_wins;
create policy "active staff can read free prize wins"
on public.free_prize_wins for select
to authenticated
using (public.current_user_is_active_staff());

revoke all on public.free_prize_wins from anon;
grant select on public.free_prize_wins to authenticated;
revoke insert, update, delete on public.free_prize_wins from authenticated;

create or replace function public.get_available_free_wheel(
  p_month_start date,
  p_category_slug text,
  p_tier_slug text
)
returns table(
  inventory_id bigint,
  prize_id bigint,
  prize_name text,
  required_tier_name text,
  weight numeric,
  quantity_remaining integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  m date := date_trunc('month', p_month_start)::date;
  cid bigint;
  selected_tier_min integer;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Not authorized';
  end if;

  select c.id into cid
  from public.wheel_categories c
  where c.slug = p_category_slug and c.active;

  select t.min_spins into selected_tier_min
  from public.wheel_tiers t
  where t.slug = p_tier_slug and t.active;

  if cid is null or selected_tier_min is null then
    raise exception 'Wheel unavailable';
  end if;

  return query
  select i.id,
         p.id,
         p.name,
         rt.name,
         i.weight,
         i.quantity_remaining
  from public.wheel_inventory i
  join public.wheel_prizes p on p.id = i.prize_id
  join public.wheel_tiers rt on rt.id = p.required_tier_id
  where p.active
    and p.category_id = cid
    and rt.active
    and rt.min_spins <= selected_tier_min
    and i.month_start = m
    and i.enabled
    and i.quantity_remaining > 0
    and i.weight > 0
  order by p.id;
end;
$$;

create or replace function public.spin_free_reward_wheel(
  p_child_id bigint,
  p_month_start date,
  p_category_slug text,
  p_tier_slug text,
  p_reason text default null
)
returns table(
  win_id bigint,
  prize_id bigint,
  prize_name text,
  category_name text,
  tier_name text,
  quantity_remaining integer,
  won_at timestamptz
)
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  m date := date_trunc('month', p_month_start)::date;
  cid bigint;
  cname text;
  tid bigint;
  tname text;
  tmin integer;
  iid bigint;
  pid bigint;
  pname text;
  left_qty integer;
  wid bigint;
  won_time timestamptz;
  target_weight numeric;
  total_weight numeric;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Not authorized';
  end if;

  perform 1 from public.children c where c.id = p_child_id for update;
  if not found then
    raise exception 'Child not found';
  end if;

  select c.id, c.name into cid, cname
  from public.wheel_categories c
  where c.slug = p_category_slug and c.active;

  select t.id, t.name, t.min_spins into tid, tname, tmin
  from public.wheel_tiers t
  where t.slug = p_tier_slug and t.active;

  if cid is null or tid is null then
    raise exception 'Wheel unavailable';
  end if;

  select sum(i.weight) into total_weight
  from public.wheel_inventory i
  join public.wheel_prizes p on p.id = i.prize_id
  join public.wheel_tiers rt on rt.id = p.required_tier_id
  where p.active
    and p.category_id = cid
    and rt.active
    and rt.min_spins <= tmin
    and i.month_start = m
    and i.enabled
    and i.quantity_remaining > 0
    and i.weight > 0;

  if coalesce(total_weight, 0) <= 0 then
    raise exception 'No in-stock prizes are available on this wheel';
  end if;

  target_weight := random() * total_weight;

  with q as (
    select i.id as inventory_key,
           p.id as prize_key,
           p.name as prize_label,
           sum(i.weight) over (order by p.id) as running_weight
    from public.wheel_inventory i
    join public.wheel_prizes p on p.id = i.prize_id
    join public.wheel_tiers rt on rt.id = p.required_tier_id
    where p.active
      and p.category_id = cid
      and rt.active
      and rt.min_spins <= tmin
      and i.month_start = m
      and i.enabled
      and i.quantity_remaining > 0
      and i.weight > 0
  )
  select q.inventory_key, q.prize_key, q.prize_label
    into iid, pid, pname
  from q
  where q.running_weight > target_weight
  order by q.running_weight
  limit 1;

  update public.wheel_inventory i
     set quantity_remaining = i.quantity_remaining - 1,
         updated_at = now()
   where i.id = iid
     and i.quantity_remaining > 0
  returning i.quantity_remaining into left_qty;

  if not found then
    raise exception 'Prize stock changed; please spin again';
  end if;

  insert into public.free_prize_wins(
    child_id,
    month_start,
    category_id,
    tier_id,
    prize_id,
    prize_name_snapshot,
    category_name_snapshot,
    tier_name_snapshot,
    reason,
    recorded_by
  )
  values(
    p_child_id,
    m,
    cid,
    tid,
    pid,
    pname,
    cname,
    tname,
    nullif(trim(coalesce(p_reason, '')), ''),
    auth.uid()
  )
  returning id, public.free_prize_wins.won_at into wid, won_time;

  return query
  select wid, pid, pname, cname, tname, left_qty, won_time;
end;
$$;

revoke all on function public.get_available_free_wheel(date, text, text) from public, anon;
grant execute on function public.get_available_free_wheel(date, text, text) to authenticated;
revoke all on function public.spin_free_reward_wheel(bigint, date, text, text, text) from public, anon;
grant execute on function public.spin_free_reward_wheel(bigint, date, text, text, text) to authenticated;;