create table if not exists public.wheel_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wheel_tiers (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  min_spins integer not null check (min_spins >= 1),
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wheel_prizes (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.wheel_categories(id) on delete restrict,
  name text not null,
  required_tier_id bigint not null references public.wheel_tiers(id) on delete restrict,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, name)
);

create table if not exists public.wheel_inventory (
  id bigint generated by default as identity primary key,
  prize_id bigint not null references public.wheel_prizes(id) on delete cascade,
  month_start date not null check (month_start = date_trunc('month', month_start)::date),
  quantity_start integer not null default 0 check (quantity_start >= 0),
  quantity_remaining integer not null default 0 check (quantity_remaining >= 0),
  weight numeric(10,2) not null default 1 check (weight > 0),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prize_id, month_start),
  check (quantity_remaining <= quantity_start)
);

create table if not exists public.prize_wins (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete restrict,
  month_start date not null check (month_start = date_trunc('month', month_start)::date),
  category_id bigint not null references public.wheel_categories(id) on delete restrict,
  tier_id bigint not null references public.wheel_tiers(id) on delete restrict,
  prize_id bigint not null references public.wheel_prizes(id) on delete restrict,
  spin_number integer not null check (spin_number >= 1),
  earned_spins_snapshot integer not null check (earned_spins_snapshot >= 1),
  prize_name_snapshot text not null,
  category_name_snapshot text not null,
  tier_name_snapshot text not null,
  recorded_by uuid not null references auth.users(id) on delete restrict,
  won_at timestamptz not null default now(),
  unique (child_id, month_start, spin_number)
);

insert into public.wheel_categories (slug, name, display_order)
values ('candy','Candy',1),('toys','Toys',2),('food','Food',3)
on conflict (slug) do update set name=excluded.name, display_order=excluded.display_order, active=true;

insert into public.wheel_tiers (slug, name, min_spins, display_order)
values ('normal','Normal',1,1),('premium','Premium',2,2),('special','Special',3,3)
on conflict (slug) do update set name=excluded.name, min_spins=excluded.min_spins, display_order=excluded.display_order, active=true;

alter table public.wheel_categories enable row level security;
alter table public.wheel_tiers enable row level security;
alter table public.wheel_prizes enable row level security;
alter table public.wheel_inventory enable row level security;
alter table public.prize_wins enable row level security;

drop policy if exists "active staff can view wheel categories" on public.wheel_categories;
create policy "active staff can view wheel categories" on public.wheel_categories for select to authenticated using (public.current_user_is_active_staff());
drop policy if exists "admins can manage wheel categories" on public.wheel_categories;
create policy "admins can manage wheel categories" on public.wheel_categories for all to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists "active staff can view wheel tiers" on public.wheel_tiers;
create policy "active staff can view wheel tiers" on public.wheel_tiers for select to authenticated using (public.current_user_is_active_staff());
drop policy if exists "admins can manage wheel tiers" on public.wheel_tiers;
create policy "admins can manage wheel tiers" on public.wheel_tiers for all to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists "active staff can view wheel prizes" on public.wheel_prizes;
create policy "active staff can view wheel prizes" on public.wheel_prizes for select to authenticated using (public.current_user_is_active_staff());
drop policy if exists "admins can manage wheel prizes" on public.wheel_prizes;
create policy "admins can manage wheel prizes" on public.wheel_prizes for all to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists "active staff can view wheel inventory" on public.wheel_inventory;
create policy "active staff can view wheel inventory" on public.wheel_inventory for select to authenticated using (public.current_user_is_active_staff());
drop policy if exists "admins can manage wheel inventory" on public.wheel_inventory;
create policy "admins can manage wheel inventory" on public.wheel_inventory for all to authenticated using (public.current_user_is_admin()) with check (public.current_user_is_admin());

drop policy if exists "active staff can view prize wins" on public.prize_wins;
create policy "active staff can view prize wins" on public.prize_wins for select to authenticated using (public.current_user_is_active_staff());

revoke all on public.wheel_categories, public.wheel_tiers, public.wheel_prizes, public.wheel_inventory, public.prize_wins from anon;
grant select on public.wheel_categories, public.wheel_tiers, public.wheel_prizes, public.wheel_inventory, public.prize_wins to authenticated;
grant insert, update, delete on public.wheel_categories, public.wheel_tiers, public.wheel_prizes, public.wheel_inventory to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.reward_earned_spins(p_child_id bigint, p_month_start date)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_points numeric := 0;
  v_points_per_spin numeric := 0;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Not authorized';
  end if;
  select coalesce(sum(points),0) into v_points
  from public.behavior_entries
  where child_id = p_child_id
    and entry_date >= date_trunc('month', p_month_start)::date
    and entry_date < (date_trunc('month', p_month_start) + interval '1 month')::date;
  select coalesce(points_per_spin,0) into v_points_per_spin from public.app_settings where id=1;
  if v_points_per_spin <= 0 then return 0; end if;
  return greatest(0, round(v_points / v_points_per_spin)::integer);
end;
$$;

create or replace function public.get_reward_roster(p_month_start date)
returns table (
  child_id bigint,
  child_name text,
  child_active boolean,
  earned_spins integer,
  used_spins integer,
  remaining_spins integer,
  tier_id bigint,
  tier_slug text,
  tier_name text
)
language sql
stable
security definer
set search_path = public
as $$
  with guard as (
    select case when public.current_user_is_active_staff() then 1 else (select 1/0) end ok
  ), totals as (
    select c.id child_id,
           trim(c.first_name || case when c.last_name is not null and c.last_name <> '' then ' ' || c.last_name else '' end) child_name,
           c.active child_active,
           public.reward_earned_spins(c.id, p_month_start) earned_spins,
           (select count(*)::integer from public.prize_wins w where w.child_id=c.id and w.month_start=date_trunc('month',p_month_start)::date) used_spins
    from public.children c, guard
  )
  select t.child_id, t.child_name, t.child_active, t.earned_spins, t.used_spins,
         greatest(0, t.earned_spins - t.used_spins) remaining_spins,
         wt.id, wt.slug, wt.name
  from totals t
  left join lateral (
    select id, slug, name
    from public.wheel_tiers
    where active and min_spins <= t.earned_spins
    order by min_spins desc, display_order desc
    limit 1
  ) wt on true
  where t.earned_spins > 0 or t.used_spins > 0
  order by t.child_name;
$$;

create or replace function public.get_available_wheel(p_child_id bigint, p_month_start date, p_category_slug text)
returns table (
  prize_id bigint,
  prize_name text,
  weight numeric,
  quantity_remaining integer,
  required_tier_slug text,
  required_tier_name text,
  unlocked_tier_slug text,
  unlocked_tier_name text,
  earned_spins integer,
  used_spins integer,
  remaining_spins integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_earned integer;
  v_used integer;
  v_unlocked_min integer;
  v_unlocked_slug text;
  v_unlocked_name text;
begin
  if not public.current_user_is_active_staff() then raise exception 'Not authorized'; end if;
  v_earned := public.reward_earned_spins(p_child_id, p_month_start);
  select count(*)::integer into v_used from public.prize_wins where child_id=p_child_id and month_start=date_trunc('month',p_month_start)::date;
  select min_spins, slug, name into v_unlocked_min, v_unlocked_slug, v_unlocked_name
  from public.wheel_tiers where active and min_spins <= v_earned order by min_spins desc limit 1;
  if coalesce(v_earned-v_used,0) <= 0 or v_unlocked_min is null then return; end if;
  return query
  select p.id, p.name, i.weight, i.quantity_remaining, rt.slug, rt.name,
         v_unlocked_slug, v_unlocked_name, v_earned, v_used, greatest(0,v_earned-v_used)
  from public.wheel_prizes p
  join public.wheel_categories c on c.id=p.category_id and c.slug=p_category_slug and c.active
  join public.wheel_tiers rt on rt.id=p.required_tier_id and rt.active and rt.min_spins <= v_unlocked_min
  join public.wheel_inventory i on i.prize_id=p.id and i.month_start=date_trunc('month',p_month_start)::date
  where p.active and i.enabled and i.quantity_remaining > 0 and i.weight > 0
  order by rt.min_spins, p.name;
end;
$$;

create or replace function public.spin_reward_wheel(p_child_id bigint, p_month_start date, p_category_slug text)
returns table (
  win_id bigint,
  prize_id bigint,
  prize_name text,
  category_name text,
  tier_name text,
  earned_spins integer,
  used_spins integer,
  remaining_spins integer,
  quantity_remaining integer
)
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_month date := date_trunc('month',p_month_start)::date;
  v_earned integer;
  v_used integer;
  v_tier_id bigint;
  v_tier_name text;
  v_tier_min integer;
  v_category_id bigint;
  v_category_name text;
  v_total_weight numeric;
  v_target numeric;
  v_prize_id bigint;
  v_prize_name text;
  v_inventory_id bigint;
  v_quantity integer;
  v_win_id bigint;
begin
  if not public.current_user_is_active_staff() then raise exception 'Not authorized'; end if;
  perform 1 from public.children where id=p_child_id for update;
  if not found then raise exception 'Child not found'; end if;

  v_earned := public.reward_earned_spins(p_child_id, v_month);
  select count(*)::integer into v_used from public.prize_wins where child_id=p_child_id and month_start=v_month;
  if v_earned <= v_used then raise exception 'No spins remaining'; end if;

  select id, name, min_spins into v_tier_id, v_tier_name, v_tier_min
  from public.wheel_tiers where active and min_spins <= v_earned order by min_spins desc limit 1;
  if v_tier_id is null then raise exception 'No unlocked wheel tier'; end if;

  select id, name into v_category_id, v_category_name from public.wheel_categories where slug=p_category_slug and active;
  if v_category_id is null then raise exception 'Wheel category is unavailable'; end if;

  select sum(i.weight) into v_total_weight
  from public.wheel_inventory i
  join public.wheel_prizes p on p.id=i.prize_id and p.active and p.category_id=v_category_id
  join public.wheel_tiers rt on rt.id=p.required_tier_id and rt.active and rt.min_spins <= v_tier_min
  where i.month_start=v_month and i.enabled and i.quantity_remaining>0 and i.weight>0;
  if coalesce(v_total_weight,0) <= 0 then raise exception 'No in-stock prizes are available on this wheel'; end if;

  v_target := random() * v_total_weight;
  with eligible as (
    select i.id inventory_id, p.id prize_id, p.name prize_name, i.weight,
           sum(i.weight) over(order by p.id) cumulative
    from public.wheel_inventory i
    join public.wheel_prizes p on p.id=i.prize_id and p.active and p.category_id=v_category_id
    join public.wheel_tiers rt on rt.id=p.required_tier_id and rt.active and rt.min_spins <= v_tier_min
    where i.month_start=v_month and i.enabled and i.quantity_remaining>0 and i.weight>0
  )
  select inventory_id, prize_id, prize_name into v_inventory_id, v_prize_id, v_prize_name
  from eligible where cumulative > v_target order by cumulative limit 1;

  update public.wheel_inventory
  set quantity_remaining=quantity_remaining-1, updated_at=now()
  where id=v_inventory_id and quantity_remaining>0
  returning quantity_remaining into v_quantity;
  if not found then raise exception 'Prize stock changed; please spin again'; end if;

  insert into public.prize_wins(child_id,month_start,category_id,tier_id,prize_id,spin_number,earned_spins_snapshot,prize_name_snapshot,category_name_snapshot,tier_name_snapshot,recorded_by)
  values(p_child_id,v_month,v_category_id,v_tier_id,v_prize_id,v_used+1,v_earned,v_prize_name,v_category_name,v_tier_name,auth.uid())
  returning id into v_win_id;

  return query select v_win_id,v_prize_id,v_prize_name,v_category_name,v_tier_name,v_earned,v_used+1,greatest(0,v_earned-v_used-1),v_quantity;
end;
$$;

grant execute on function public.reward_earned_spins(bigint,date) to authenticated;
grant execute on function public.get_reward_roster(date) to authenticated;
grant execute on function public.get_available_wheel(bigint,date,text) to authenticated;
grant execute on function public.spin_reward_wheel(bigint,date,text) to authenticated;;