alter table public.learning_student_assignments
  add column if not exists schedule_id bigint,
  add column if not exists occurrence_date date;

alter table public.learning_student_assignments
  drop constraint if exists learning_student_assignments_child_id_assignment_id_week_st_key;

drop index if exists public.learning_student_assignments_once_unique_idx;
create unique index learning_student_assignments_once_unique_idx
  on public.learning_student_assignments(child_id, assignment_id, week_start)
  where occurrence_date is null;

drop index if exists public.learning_student_assignments_occurrence_unique_idx;
create unique index learning_student_assignments_occurrence_unique_idx
  on public.learning_student_assignments(child_id, assignment_id, occurrence_date)
  where occurrence_date is not null;

alter table public.learning_student_assignments
  drop constraint if exists learning_student_assignments_occurrence_in_week_check;

alter table public.learning_student_assignments
  add constraint learning_student_assignments_occurrence_in_week_check
  check (
    occurrence_date is null
    or (occurrence_date >= week_start and occurrence_date <= week_start + 6)
  );

create table if not exists public.learning_assignment_schedules (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete cascade,
  assignment_id bigint not null references public.learning_assignments(id) on delete restrict,
  repeat_mode text not null check (repeat_mode = any (array['daily'::text,'weekdays'::text,'weekly'::text,'custom'::text])),
  days_of_week smallint[] not null,
  start_date date not null,
  end_date date not null,
  active boolean not null default true,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  constraint learning_assignment_schedules_dates_check check (end_date >= start_date),
  constraint learning_assignment_schedules_days_check check (
    cardinality(days_of_week) between 1 and 7
    and days_of_week <@ array[0,1,2,3,4,5,6]::smallint[]
  )
);

create index if not exists learning_assignment_schedules_child_idx
  on public.learning_assignment_schedules(child_id, active, start_date, end_date);
create index if not exists learning_assignment_schedules_assignment_idx
  on public.learning_assignment_schedules(assignment_id, active);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid='public.learning_student_assignments'::regclass
      and conname='learning_student_assignments_schedule_id_fkey'
  ) then
    alter table public.learning_student_assignments
      add constraint learning_student_assignments_schedule_id_fkey
      foreign key (schedule_id)
      references public.learning_assignment_schedules(id)
      on delete set null;
  end if;
end $$;

alter table public.learning_assignment_schedules enable row level security;

drop policy if exists "active staff can view learning assignment schedules" on public.learning_assignment_schedules;
create policy "active staff can view learning assignment schedules"
on public.learning_assignment_schedules
for select to authenticated
using ((select public.current_user_is_active_staff()));

drop policy if exists "active staff can create learning assignment schedules" on public.learning_assignment_schedules;
create policy "active staff can create learning assignment schedules"
on public.learning_assignment_schedules
for insert to authenticated
with check (
  (select public.current_user_is_active_staff())
  and created_by = (select auth.uid())
  and updated_by = (select auth.uid())
);

drop policy if exists "active staff can update learning assignment schedules" on public.learning_assignment_schedules;
create policy "active staff can update learning assignment schedules"
on public.learning_assignment_schedules
for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

drop policy if exists "admins can delete learning assignment schedules" on public.learning_assignment_schedules;
create policy "admins can delete learning assignment schedules"
on public.learning_assignment_schedules
for delete to authenticated
using ((select public.current_user_is_admin()));

grant select, insert, update, delete on public.learning_assignment_schedules to authenticated;
grant usage, select on sequence public.learning_assignment_schedules_id_seq to authenticated;

create or replace function public.create_learning_recurring_assignments(
  p_assignment_id bigint,
  p_child_ids bigint[],
  p_start_date date,
  p_end_date date,
  p_repeat_mode text,
  p_days smallint[] default null
)
returns jsonb
language plpgsql
security invoker
set search_path to 'public'
as $function$
declare
  v_uid uuid := auth.uid();
  v_days smallint[];
  v_child_id bigint;
  v_schedule_id bigint;
  v_schedule_count integer := 0;
  v_occurrence_count integer := 0;
  v_skipped_count integer := 0;
  v_inserted integer := 0;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  if p_assignment_id is null
     or p_child_ids is null
     or cardinality(p_child_ids) = 0
     or p_start_date is null
     or p_end_date is null then
    raise exception 'Assignment, student, start date, and end date are required';
  end if;

  if p_end_date < p_start_date then
    raise exception 'Repeat end date must be on or after the start date';
  end if;

  if p_end_date > p_start_date + 366 then
    raise exception 'Recurring assignments can be scheduled up to one year at a time';
  end if;

  if not exists (
    select 1 from public.learning_assignments
    where id = p_assignment_id and active
  ) then
    raise exception 'That assignment is not active';
  end if;

  if p_repeat_mode = 'daily' then
    v_days := array[0,1,2,3,4,5,6]::smallint[];
  elsif p_repeat_mode = 'weekdays' then
    v_days := array[1,2,3,4,5]::smallint[];
  elsif p_repeat_mode = 'weekly' then
    v_days := array[extract(dow from p_start_date)::smallint];
  elsif p_repeat_mode = 'custom' then
    select coalesce(array_agg(distinct day_value order by day_value), array[]::smallint[])
      into v_days
    from unnest(coalesce(p_days, array[]::smallint[])) as day_value
    where day_value between 0 and 6;

    if cardinality(v_days) = 0 then
      raise exception 'Choose at least one day for a custom schedule';
    end if;
  else
    raise exception 'Invalid repeat mode';
  end if;

  for v_child_id in
    select distinct c.id
    from public.children c
    where c.active
      and c.id = any(p_child_ids)
    order by c.id
  loop
    if exists (
      select 1
      from public.learning_assignment_schedules s
      where s.child_id = v_child_id
        and s.assignment_id = p_assignment_id
        and s.active
        and daterange(s.start_date, s.end_date, '[]') && daterange(p_start_date, p_end_date, '[]')
    ) then
      v_skipped_count := v_skipped_count + 1;
      continue;
    end if;

    insert into public.learning_assignment_schedules(
      child_id, assignment_id, repeat_mode, days_of_week,
      start_date, end_date, active, created_by, updated_by
    )
    values (
      v_child_id, p_assignment_id, p_repeat_mode, v_days,
      p_start_date, p_end_date, true, v_uid, v_uid
    )
    returning id into v_schedule_id;

    v_schedule_count := v_schedule_count + 1;

    insert into public.learning_student_assignments(
      child_id, assignment_id, week_start, due_date,
      schedule_id, occurrence_date,
      status, assigned_by, updated_by
    )
    select
      v_child_id,
      p_assignment_id,
      (d::date - (extract(isodow from d)::integer - 1)),
      d::date,
      v_schedule_id,
      d::date,
      'assigned',
      v_uid,
      v_uid
    from generate_series(
      p_start_date::timestamp,
      p_end_date::timestamp,
      interval '1 day'
    ) as d
    where extract(dow from d)::smallint = any(v_days)
    on conflict do nothing;

    get diagnostics v_inserted = row_count;
    v_occurrence_count := v_occurrence_count + v_inserted;
  end loop;

  return jsonb_build_object(
    'schedules_created', v_schedule_count,
    'occurrences_created', v_occurrence_count,
    'students_skipped', v_skipped_count
  );
end;
$function$;

revoke all on function public.create_learning_recurring_assignments(bigint,bigint[],date,date,text,smallint[]) from public;
revoke all on function public.create_learning_recurring_assignments(bigint,bigint[],date,date,text,smallint[]) from anon;
grant execute on function public.create_learning_recurring_assignments(bigint,bigint[],date,date,text,smallint[]) to authenticated;

create or replace function public.stop_learning_assignment_schedule(
  p_schedule_id bigint,
  p_stop_date date
)
returns jsonb
language plpgsql
security invoker
set search_path to 'public'
as $function$
declare
  v_uid uuid := auth.uid();
  v_deleted integer := 0;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  if p_schedule_id is null or p_stop_date is null then
    raise exception 'Schedule and stop date are required';
  end if;

  update public.learning_assignment_schedules
  set active = false,
      end_date = greatest(start_date, least(end_date, p_stop_date - 1)),
      updated_by = v_uid,
      updated_at = now()
  where id = p_schedule_id;

  if not found then
    raise exception 'Recurring schedule not found';
  end if;

  delete from public.learning_student_assignments a
  where a.schedule_id = p_schedule_id
    and a.occurrence_date >= p_stop_date
    and a.status = 'assigned'
    and a.completed_at is null
    and a.score is null
    and a.max_score is null
    and a.minutes_spent is null
    and a.staff_note is null
    and not exists (select 1 from public.learning_typing_attempts t where t.student_assignment_id = a.id)
    and not exists (select 1 from public.learning_quiz_attempts q where q.student_assignment_id = a.id)
    and not exists (select 1 from public.learning_writing_submissions w where w.student_assignment_id = a.id)
    and not exists (select 1 from public.learning_reading_attempts r where r.student_assignment_id = a.id);

  get diagnostics v_deleted = row_count;

  return jsonb_build_object(
    'stopped', true,
    'future_occurrences_removed', v_deleted
  );
end;
$function$;

revoke all on function public.stop_learning_assignment_schedule(bigint,date) from public;
revoke all on function public.stop_learning_assignment_schedule(bigint,date) from anon;
grant execute on function public.stop_learning_assignment_schedule(bigint,date) to authenticated;
