
create table if not exists public.learning_progress_report_comments (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  summary text not null default '',
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint learning_progress_report_comments_period_check check (period_end >= period_start),
  constraint learning_progress_report_comments_unique unique (child_id, period_start, period_end)
);

alter table public.learning_progress_report_comments enable row level security;

drop policy if exists "active staff can view progress report comments" on public.learning_progress_report_comments;
create policy "active staff can view progress report comments"
on public.learning_progress_report_comments
for select
to authenticated
using (
  exists (
    select 1 from public.staff_profiles sp
    where sp.user_id = (select auth.uid()) and sp.active
  )
);

drop policy if exists "active staff can add progress report comments" on public.learning_progress_report_comments;
create policy "active staff can add progress report comments"
on public.learning_progress_report_comments
for insert
to authenticated
with check (
  updated_by = (select auth.uid())
  and exists (
    select 1 from public.staff_profiles sp
    where sp.user_id = (select auth.uid()) and sp.active
  )
);

drop policy if exists "active staff can update progress report comments" on public.learning_progress_report_comments;
create policy "active staff can update progress report comments"
on public.learning_progress_report_comments
for update
to authenticated
using (
  exists (
    select 1 from public.staff_profiles sp
    where sp.user_id = (select auth.uid()) and sp.active
  )
)
with check (
  updated_by = (select auth.uid())
  and exists (
    select 1 from public.staff_profiles sp
    where sp.user_id = (select auth.uid()) and sp.active
  )
);

revoke all on public.learning_progress_report_comments from anon;
grant select, insert, update on public.learning_progress_report_comments to authenticated;
grant usage, select on sequence public.learning_progress_report_comments_id_seq to authenticated;

create index if not exists learning_progress_report_comments_child_period_idx
  on public.learning_progress_report_comments(child_id, period_start, period_end);
;