alter table public.child_registrations
  add column if not exists attendance_days text[] not null default '{}'::text[],
  add column if not exists attends_other_program boolean not null default false,
  add column if not exists other_program_arrival_notes text,
  add column if not exists dismissal_plan text,
  add column if not exists dismissal_notes text;

alter table public.child_guardians
  add column if not exists secondary_phone text,
  add column if not exists address text,
  add column if not exists preferred_contact text;

alter table public.child_health_info
  add column if not exists medical_conditions text,
  add column if not exists learning_support text,
  add column if not exists behavioral_support text,
  add column if not exists actions_to_take text;

create table if not exists public.child_authorized_pickups (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references public.child_registrations(id) on delete cascade,
  name text not null,
  relationship text,
  phone text,
  notes text,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists child_authorized_pickups_registration_idx on public.child_authorized_pickups(registration_id);
create index if not exists child_authorized_pickups_created_by_idx on public.child_authorized_pickups(created_by);
create index if not exists child_authorized_pickups_updated_by_idx on public.child_authorized_pickups(updated_by);

create table if not exists public.child_registration_agreements (
  registration_id bigint primary key references public.child_registrations(id) on delete cascade,
  media_consent boolean,
  program_consent boolean,
  removal_acknowledgment boolean,
  rules_acknowledgment boolean,
  friday_participation_acknowledgment boolean,
  info_accuracy_acknowledgment boolean,
  signature_name text,
  signature_date date,
  terms_version text,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.child_authorized_pickups enable row level security;
alter table public.child_registration_agreements enable row level security;

revoke all on public.child_authorized_pickups from anon;
revoke all on public.child_registration_agreements from anon;
grant select, insert, update, delete on public.child_authorized_pickups to authenticated;
grant select, insert, update, delete on public.child_registration_agreements to authenticated;

create policy "admins can view authorized pickups" on public.child_authorized_pickups
for select to authenticated using ((select public.current_user_is_admin()));
create policy "admins can insert authorized pickups" on public.child_authorized_pickups
for insert to authenticated with check ((select public.current_user_is_admin()) and created_by = (select auth.uid()) and updated_by = (select auth.uid()));
create policy "admins can update authorized pickups" on public.child_authorized_pickups
for update to authenticated using ((select public.current_user_is_admin())) with check ((select public.current_user_is_admin()) and updated_by = (select auth.uid()));
create policy "admins can delete authorized pickups" on public.child_authorized_pickups
for delete to authenticated using ((select public.current_user_is_admin()));

create policy "admins can view registration agreements" on public.child_registration_agreements
for select to authenticated using ((select public.current_user_is_admin()));
create policy "admins can insert registration agreements" on public.child_registration_agreements
for insert to authenticated with check ((select public.current_user_is_admin()) and created_by = (select auth.uid()) and updated_by = (select auth.uid()));
create policy "admins can update registration agreements" on public.child_registration_agreements
for update to authenticated using ((select public.current_user_is_admin())) with check ((select public.current_user_is_admin()) and updated_by = (select auth.uid()));
create policy "admins can delete registration agreements" on public.child_registration_agreements
for delete to authenticated using ((select public.current_user_is_admin()));
;