alter table public.staff_profiles
  add column if not exists can_view_sensitive_child_info boolean not null default false;

create table if not exists public.child_registrations (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete restrict,
  school_year text not null,
  birth_date date,
  school text,
  grade text,
  status text not null default 'active' check (status in ('active','expired')),
  show_birthday_publicly boolean not null default true,
  registered_at timestamptz not null default now(),
  expired_at timestamptz,
  created_by uuid not null references public.staff_profiles(user_id) on delete restrict,
  updated_by uuid not null references public.staff_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (child_id, school_year)
);

create unique index if not exists child_registrations_one_active_per_child_idx
  on public.child_registrations(child_id)
  where status = 'active';
create index if not exists child_registrations_status_idx on public.child_registrations(status, child_id);
create index if not exists child_registrations_birth_date_idx on public.child_registrations(birth_date) where status = 'active';
create index if not exists child_registrations_created_by_idx on public.child_registrations(created_by);
create index if not exists child_registrations_updated_by_idx on public.child_registrations(updated_by);

create table if not exists public.child_guardians (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references public.child_registrations(id) on delete cascade,
  name text not null,
  relationship text,
  phone text,
  email text,
  is_primary boolean not null default false,
  is_emergency boolean not null default false,
  authorized_pickup boolean not null default false,
  notes text,
  created_by uuid not null references public.staff_profiles(user_id) on delete restrict,
  updated_by uuid not null references public.staff_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists child_guardians_registration_idx on public.child_guardians(registration_id);
create index if not exists child_guardians_created_by_idx on public.child_guardians(created_by);
create index if not exists child_guardians_updated_by_idx on public.child_guardians(updated_by);

create table if not exists public.child_health_info (
  registration_id bigint primary key references public.child_registrations(id) on delete cascade,
  allergies text,
  important_care_notes text,
  created_by uuid not null references public.staff_profiles(user_id) on delete restrict,
  updated_by uuid not null references public.staff_profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists child_health_info_created_by_idx on public.child_health_info(created_by);
create index if not exists child_health_info_updated_by_idx on public.child_health_info(updated_by);

create table if not exists public.child_profile_audit (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete restrict,
  registration_id bigint references public.child_registrations(id) on delete set null,
  area text not null check (area in ('registration','guardian','health')),
  action text not null check (action in ('insert','update','delete')),
  changed_by uuid references public.staff_profiles(user_id) on delete set null,
  changed_at timestamptz not null default now()
);
create index if not exists child_profile_audit_child_idx on public.child_profile_audit(child_id, changed_at desc);
create index if not exists child_profile_audit_registration_idx on public.child_profile_audit(registration_id, changed_at desc);
create index if not exists child_profile_audit_changed_by_idx on public.child_profile_audit(changed_by);

create or replace function public.set_child_profile_updated_fields()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

create or replace function public.audit_child_registration_change()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.child_profile_audit(child_id, registration_id, area, action, changed_by)
    values (old.child_id, old.id, 'registration', 'delete', auth.uid());
    return old;
  elsif tg_op = 'INSERT' then
    insert into public.child_profile_audit(child_id, registration_id, area, action, changed_by)
    values (new.child_id, new.id, 'registration', 'insert', auth.uid());
    return new;
  else
    insert into public.child_profile_audit(child_id, registration_id, area, action, changed_by)
    values (new.child_id, new.id, 'registration', 'update', auth.uid());
    return new;
  end if;
end;
$$;

create or replace function public.audit_child_guardian_change()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_registration_id bigint;
  v_child_id bigint;
begin
  v_registration_id := case when tg_op = 'DELETE' then old.registration_id else new.registration_id end;
  select child_id into v_child_id from public.child_registrations where id = v_registration_id;
  insert into public.child_profile_audit(child_id, registration_id, area, action, changed_by)
  values (v_child_id, v_registration_id, 'guardian', lower(tg_op), auth.uid());
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function public.audit_child_health_change()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_registration_id bigint;
  v_child_id bigint;
begin
  v_registration_id := case when tg_op = 'DELETE' then old.registration_id else new.registration_id end;
  select child_id into v_child_id from public.child_registrations where id = v_registration_id;
  insert into public.child_profile_audit(child_id, registration_id, area, action, changed_by)
  values (v_child_id, v_registration_id, 'health', lower(tg_op), auth.uid());
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists child_registrations_set_updated on public.child_registrations;
create trigger child_registrations_set_updated before update on public.child_registrations
for each row execute function public.set_child_profile_updated_fields();
drop trigger if exists child_guardians_set_updated on public.child_guardians;
create trigger child_guardians_set_updated before update on public.child_guardians
for each row execute function public.set_child_profile_updated_fields();
drop trigger if exists child_health_info_set_updated on public.child_health_info;
create trigger child_health_info_set_updated before update on public.child_health_info
for each row execute function public.set_child_profile_updated_fields();

drop trigger if exists child_registrations_audit on public.child_registrations;
create trigger child_registrations_audit after insert or update or delete on public.child_registrations
for each row execute function public.audit_child_registration_change();
drop trigger if exists child_guardians_audit on public.child_guardians;
create trigger child_guardians_audit after insert or update or delete on public.child_guardians
for each row execute function public.audit_child_guardian_change();
drop trigger if exists child_health_info_audit on public.child_health_info;
create trigger child_health_info_audit after insert or update or delete on public.child_health_info
for each row execute function public.audit_child_health_change();

alter table public.child_registrations enable row level security;
alter table public.child_guardians enable row level security;
alter table public.child_health_info enable row level security;
alter table public.child_profile_audit enable row level security;

drop policy if exists "active staff can view child registrations" on public.child_registrations;
create policy "active staff can view child registrations"
on public.child_registrations for select to authenticated
using ((select public.current_user_is_active_staff()));

drop policy if exists "admins can manage child registrations" on public.child_registrations;
create policy "admins can manage child registrations"
on public.child_registrations for all to authenticated
using ((select public.current_user_is_admin()))
with check ((select public.current_user_is_admin()) and created_by is not null and updated_by is not null);

drop policy if exists "admins can view child guardians" on public.child_guardians;
create policy "admins can view child guardians"
on public.child_guardians for select to authenticated
using ((select public.current_user_is_admin()));
drop policy if exists "admins can manage child guardians" on public.child_guardians;
create policy "admins can manage child guardians"
on public.child_guardians for all to authenticated
using ((select public.current_user_is_admin()))
with check ((select public.current_user_is_admin()) and created_by is not null and updated_by is not null);

drop policy if exists "admins can view child health info" on public.child_health_info;
create policy "admins can view child health info"
on public.child_health_info for select to authenticated
using ((select public.current_user_is_admin()));
drop policy if exists "admins can manage child health info" on public.child_health_info;
create policy "admins can manage child health info"
on public.child_health_info for all to authenticated
using ((select public.current_user_is_admin()))
with check ((select public.current_user_is_admin()) and created_by is not null and updated_by is not null);

drop policy if exists "admins can view child profile audit" on public.child_profile_audit;
create policy "admins can view child profile audit"
on public.child_profile_audit for select to authenticated
using ((select public.current_user_is_admin()));
drop policy if exists "active staff can insert child profile audit" on public.child_profile_audit;
create policy "active staff can insert child profile audit"
on public.child_profile_audit for insert to authenticated
with check ((select public.current_user_is_active_staff()) and changed_by = (select auth.uid()));

revoke all on public.child_registrations from anon;
revoke all on public.child_guardians from anon;
revoke all on public.child_health_info from anon;
revoke all on public.child_profile_audit from anon;

grant select, insert, update, delete on public.child_registrations to authenticated;
grant select, insert, update, delete on public.child_guardians to authenticated;
grant select, insert, update, delete on public.child_health_info to authenticated;
grant select, insert on public.child_profile_audit to authenticated;

grant usage, select on sequence public.child_registrations_id_seq to authenticated;
grant usage, select on sequence public.child_guardians_id_seq to authenticated;
grant usage, select on sequence public.child_profile_audit_id_seq to authenticated;;