
create table if not exists public.learning_goals (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete cascade,
  goal_type text not null check (goal_type in (
    'assignment_completions','reading_minutes','writing_submissions',
    'quiz_consistency','typing_accuracy','typing_wpm','custom'
  )),
  title text not null,
  description text,
  start_date date not null default current_date,
  end_date date not null,
  target_value numeric not null default 1 check (target_value > 0),
  target_count integer not null default 1 check (target_count between 1 and 50),
  current_value numeric not null default 0 check (current_value >= 0),
  current_count integer not null default 0 check (current_count >= 0),
  reward_points numeric not null default 1 check (reward_points = 1),
  status text not null default 'active' check (status in ('active','reached','approved','expired','cancelled')),
  config jsonb not null default '{}'::jsonb check (jsonb_typeof(config)='object'),
  reached_at timestamptz,
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint learning_goals_date_check check (end_date >= start_date)
);

create table if not exists public.learning_goal_bonus_points (
  id bigint generated by default as identity primary key,
  goal_id bigint not null unique references public.learning_goals(id) on delete restrict,
  child_id bigint not null references public.children(id) on delete restrict,
  points numeric not null default 1 check (points = 1),
  awarded_on date not null default current_date,
  awarded_by uuid not null references auth.users(id),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.learning_student_achievements (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete cascade,
  achievement_key text not null,
  title text not null,
  description text not null,
  icon text not null,
  unlocked_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  unique(child_id,achievement_key)
);

create index if not exists learning_goals_child_status_idx on public.learning_goals(child_id,status,end_date);
create index if not exists learning_goal_bonus_points_child_date_idx on public.learning_goal_bonus_points(child_id,awarded_on);
create index if not exists learning_student_achievements_child_date_idx on public.learning_student_achievements(child_id,unlocked_at desc);

alter table public.learning_goals enable row level security;
alter table public.learning_goal_bonus_points enable row level security;
alter table public.learning_student_achievements enable row level security;

drop policy if exists "active staff can view learning goals" on public.learning_goals;
create policy "active staff can view learning goals"
on public.learning_goals for select to authenticated
using (public.current_user_is_active_staff());

drop policy if exists "active staff can add learning goals" on public.learning_goals;
create policy "active staff can add learning goals"
on public.learning_goals for insert to authenticated
with check (public.current_user_is_active_staff() and created_by=(select auth.uid()));

drop policy if exists "active staff can update learning goals" on public.learning_goals;
create policy "active staff can update learning goals"
on public.learning_goals for update to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

drop policy if exists "active staff can view learning goal bonuses" on public.learning_goal_bonus_points;
create policy "active staff can view learning goal bonuses"
on public.learning_goal_bonus_points for select to authenticated
using (public.current_user_is_active_staff());

drop policy if exists "active staff can award learning goal bonuses" on public.learning_goal_bonus_points;
create policy "active staff can award learning goal bonuses"
on public.learning_goal_bonus_points for insert to authenticated
with check (
  public.current_user_is_active_staff()
  and awarded_by = (select auth.uid())
  and points = 1
  and exists (
    select 1
    from public.learning_goals g
    where g.id = goal_id
      and g.child_id = learning_goal_bonus_points.child_id
      and g.status = 'approved'
      and g.reward_points = learning_goal_bonus_points.points
  )
);

drop policy if exists "active staff can view learning achievements" on public.learning_student_achievements;
create policy "active staff can view learning achievements"
on public.learning_student_achievements for select to authenticated
using (public.current_user_is_active_staff());

drop policy if exists "active staff can add learning achievements" on public.learning_student_achievements;
create policy "active staff can add learning achievements"
on public.learning_student_achievements for insert to authenticated
with check (public.current_user_is_active_staff());

grant select,insert,update on public.learning_goals to authenticated;
grant usage,select on sequence public.learning_goals_id_seq to authenticated;
grant select,insert on public.learning_goal_bonus_points to authenticated;
grant usage,select on sequence public.learning_goal_bonus_points_id_seq to authenticated;
grant select,insert on public.learning_student_achievements to authenticated;
grant usage,select on sequence public.learning_student_achievements_id_seq to authenticated;

grant select,insert,update,delete on public.learning_goals to service_role;
grant select,insert,update,delete on public.learning_goal_bonus_points to service_role;
grant select,insert,update,delete on public.learning_student_achievements to service_role;

create or replace function public.validate_learning_goal_open_limit()
returns trigger
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_open integer;
begin
  new.title := nullif(trim(coalesce(new.title,'')),'');
  if new.title is null then raise exception 'Goal title is required'; end if;
  new.updated_at := now();

  if new.status in ('active','reached') then
    select count(*) into v_open
    from public.learning_goals g
    where g.child_id=new.child_id
      and g.status in ('active','reached')
      and (tg_op='INSERT' or g.id<>new.id);
    if v_open >= 2 then
      raise exception 'A student can have at most two open point-earning goals at a time.';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists learning_goals_open_limit on public.learning_goals;
create trigger learning_goals_open_limit
before insert or update on public.learning_goals
for each row execute function public.validate_learning_goal_open_limit();
;