alter table public.programs
  add column if not exists public_registration_id uuid not null default gen_random_uuid(),
  add column if not exists registration_public boolean not null default false,
  add column if not exists registration_intro text;

create unique index if not exists programs_public_registration_id_uidx
  on public.programs(public_registration_id);

create table if not exists public.program_registration_consents (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete cascade,
  title text not null check (length(btrim(title)) between 1 and 160),
  body text not null check (length(btrim(body)) between 1 and 5000),
  required boolean not null default true,
  applies_to_modes text[] not null default array['full','renewal','summer_short','permission_only','short_youth','adult_short']::text[],
  display_order smallint not null default 0,
  active boolean not null default true,
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (applies_to_modes <@ array['full','renewal','summer_short','permission_only','short_youth','adult_short']::text[])
);

create index if not exists program_registration_consents_program_idx
  on public.program_registration_consents(program_id, active, display_order);

create table if not exists public.registration_access_tokens (
  id uuid primary key default gen_random_uuid(),
  program_id bigint not null references public.programs(id) on delete cascade,
  household_id bigint not null references public.households(id) on delete cascade,
  token_hash text not null unique,
  status text not null default 'active' check (status in ('active','used','revoked')),
  expires_at timestamptz not null,
  used_at timestamptz,
  revoked_at timestamptz,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists registration_access_tokens_lookup_idx
  on public.registration_access_tokens(program_id, household_id, status, expires_at);
create index if not exists registration_access_tokens_created_by_idx
  on public.registration_access_tokens(created_by);

create table if not exists public.registration_submissions (
  id uuid primary key default gen_random_uuid(),
  submission_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  program_id bigint not null references public.programs(id) on delete restrict,
  registration_mode text not null check (registration_mode in ('full','renewal','summer_short','permission_only','short_youth','adult_short')),
  household_id bigint references public.households(id) on delete set null,
  access_token_id uuid references public.registration_access_tokens(id) on delete set null,
  status text not null default 'submitted' check (status in ('submitted','needs_review','approved','declined')),
  submitter_name text,
  submitter_email text,
  submitter_phone text,
  payload jsonb not null default '{}'::jsonb,
  client_fingerprint text,
  review_notes text,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(payload) = 'object')
);

create index if not exists registration_submissions_program_status_idx
  on public.registration_submissions(program_id, status, created_at desc);
create index if not exists registration_submissions_household_idx
  on public.registration_submissions(household_id) where household_id is not null;
create index if not exists registration_submissions_reviewed_by_idx
  on public.registration_submissions(reviewed_by) where reviewed_by is not null;
create index if not exists registration_submissions_fingerprint_idx
  on public.registration_submissions(client_fingerprint, created_at desc) where client_fingerprint is not null;

create table if not exists public.registration_submission_audit (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.registration_submissions(id) on delete cascade,
  action text not null check (action in ('submitted','status_changed','approved','declined')),
  old_status text,
  new_status text,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now()
);

create index if not exists registration_submission_audit_submission_idx
  on public.registration_submission_audit(submission_id, changed_at desc);
create index if not exists registration_submission_audit_changed_by_idx
  on public.registration_submission_audit(changed_by) where changed_by is not null;

create table if not exists public.program_consent_acceptances (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete restrict,
  enrollment_id bigint references public.program_enrollments(id) on delete set null,
  submission_id uuid references public.registration_submissions(id) on delete set null,
  child_id bigint references public.children(id) on delete set null,
  adult_participant_id bigint references public.adult_participants(id) on delete set null,
  consent_id bigint references public.program_registration_consents(id) on delete set null,
  consent_title text not null,
  consent_body text not null,
  required boolean not null,
  agreed boolean not null,
  signature_name text,
  signature_date date,
  accepted_at timestamptz not null default now(),
  created_by uuid not null default auth.uid() references auth.users(id),
  check ((child_id is not null)::int + (adult_participant_id is not null)::int <= 1)
);

create index if not exists program_consent_acceptances_program_idx
  on public.program_consent_acceptances(program_id, accepted_at desc);
create index if not exists program_consent_acceptances_enrollment_idx
  on public.program_consent_acceptances(enrollment_id) where enrollment_id is not null;
create index if not exists program_consent_acceptances_created_by_idx
  on public.program_consent_acceptances(created_by);

create or replace function public.touch_registration_portal_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  if tg_table_name = 'program_registration_consents' and auth.uid() is not null then
    new.updated_by = auth.uid();
  end if;
  return new;
end;
$$;

revoke all on function public.touch_registration_portal_updated_at() from public, anon, authenticated;

drop trigger if exists program_registration_consents_touch on public.program_registration_consents;
create trigger program_registration_consents_touch
before update on public.program_registration_consents
for each row execute function public.touch_registration_portal_updated_at();

drop trigger if exists registration_submissions_touch on public.registration_submissions;
create trigger registration_submissions_touch
before update on public.registration_submissions
for each row execute function public.touch_registration_portal_updated_at();

create or replace function public.audit_registration_submission_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.registration_submission_audit(submission_id, action, new_status, changed_by)
    values (new.id, 'submitted', new.status, auth.uid());
  elsif new.status is distinct from old.status then
    insert into public.registration_submission_audit(submission_id, action, old_status, new_status, changed_by)
    values (
      new.id,
      case when new.status = 'approved' then 'approved' when new.status = 'declined' then 'declined' else 'status_changed' end,
      old.status,
      new.status,
      coalesce(new.reviewed_by, auth.uid())
    );
  end if;
  return new;
end;
$$;

revoke all on function public.audit_registration_submission_status() from public, anon, authenticated;

drop trigger if exists registration_submissions_audit on public.registration_submissions;
create trigger registration_submissions_audit
after insert or update of status on public.registration_submissions
for each row execute function public.audit_registration_submission_status();

alter table public.program_registration_consents enable row level security;
alter table public.registration_access_tokens enable row level security;
alter table public.registration_submissions enable row level security;
alter table public.registration_submission_audit enable row level security;
alter table public.program_consent_acceptances enable row level security;

revoke all on public.program_registration_consents from anon;
revoke all on public.registration_access_tokens from anon;
revoke all on public.registration_submissions from anon;
revoke all on public.registration_submission_audit from anon;
revoke all on public.program_consent_acceptances from anon;

grant select, insert, update, delete on public.program_registration_consents to authenticated;
grant select, insert, update, delete on public.registration_access_tokens to authenticated;
grant select, update, delete on public.registration_submissions to authenticated;
grant select on public.registration_submission_audit to authenticated;
grant select on public.program_consent_acceptances to authenticated;

drop policy if exists "active staff can view registration consents" on public.program_registration_consents;
create policy "active staff can view registration consents" on public.program_registration_consents
for select to authenticated using ((select public.current_user_is_active_staff()));
drop policy if exists "admins can insert registration consents" on public.program_registration_consents;
create policy "admins can insert registration consents" on public.program_registration_consents
for insert to authenticated with check ((select public.current_user_is_admin()) and created_by = (select auth.uid()));
drop policy if exists "admins can update registration consents" on public.program_registration_consents;
create policy "admins can update registration consents" on public.program_registration_consents
for update to authenticated using ((select public.current_user_is_admin())) with check ((select public.current_user_is_admin()));
drop policy if exists "admins can delete registration consents" on public.program_registration_consents;
create policy "admins can delete registration consents" on public.program_registration_consents
for delete to authenticated using ((select public.current_user_is_admin()));

drop policy if exists "admins can view registration tokens" on public.registration_access_tokens;
create policy "admins can view registration tokens" on public.registration_access_tokens
for select to authenticated using ((select public.current_user_is_admin()));
drop policy if exists "admins can insert registration tokens" on public.registration_access_tokens;
create policy "admins can insert registration tokens" on public.registration_access_tokens
for insert to authenticated with check ((select public.current_user_is_admin()) and created_by = (select auth.uid()));
drop policy if exists "admins can update registration tokens" on public.registration_access_tokens;
create policy "admins can update registration tokens" on public.registration_access_tokens
for update to authenticated using ((select public.current_user_is_admin())) with check ((select public.current_user_is_admin()));
drop policy if exists "admins can delete registration tokens" on public.registration_access_tokens;
create policy "admins can delete registration tokens" on public.registration_access_tokens
for delete to authenticated using ((select public.current_user_is_admin()));

drop policy if exists "admins can view registration submissions" on public.registration_submissions;
create policy "admins can view registration submissions" on public.registration_submissions
for select to authenticated using ((select public.current_user_is_admin()));
drop policy if exists "admins can update registration submissions" on public.registration_submissions;
create policy "admins can update registration submissions" on public.registration_submissions
for update to authenticated using ((select public.current_user_is_admin())) with check ((select public.current_user_is_admin()));
drop policy if exists "admins can delete registration submissions" on public.registration_submissions;
create policy "admins can delete registration submissions" on public.registration_submissions
for delete to authenticated using ((select public.current_user_is_admin()));

drop policy if exists "admins can view registration audit" on public.registration_submission_audit;
create policy "admins can view registration audit" on public.registration_submission_audit
for select to authenticated using ((select public.current_user_is_admin()));

drop policy if exists "admins can view consent acceptances" on public.program_consent_acceptances;
create policy "admins can view consent acceptances" on public.program_consent_acceptances
for select to authenticated using ((select public.current_user_is_admin()));

create or replace function public.create_registration_access_token(p_program_id bigint, p_household_id bigint, p_expires_days integer default 14)
returns text
language plpgsql
security invoker
set search_path = public, extensions
as $$
declare
  v_token text;
  v_hash text;
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;
  if p_expires_days < 1 or p_expires_days > 60 then
    raise exception 'Expiration must be between 1 and 60 days';
  end if;
  if not exists (select 1 from public.programs where id = p_program_id) then
    raise exception 'Program not found';
  end if;
  if not exists (select 1 from public.households where id = p_household_id and status = 'active') then
    raise exception 'Active household not found';
  end if;

  v_token := encode(gen_random_bytes(32), 'hex');
  v_hash := encode(digest(v_token, 'sha256'), 'hex');

  insert into public.registration_access_tokens(program_id, household_id, token_hash, expires_at, created_by)
  values (p_program_id, p_household_id, v_hash, now() + make_interval(days => p_expires_days), auth.uid());

  return v_token;
end;
$$;

revoke all on function public.create_registration_access_token(bigint,bigint,integer) from public, anon;
grant execute on function public.create_registration_access_token(bigint,bigint,integer) to authenticated;

create or replace function public.approve_registration_submission(p_submission_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_submission public.registration_submissions%rowtype;
  v_program public.programs%rowtype;
  v_payload jsonb;
  v_guardian jsonb;
  v_emergency jsonb;
  v_child jsonb;
  v_adult jsonb;
  v_consent jsonb;
  v_household_id bigint;
  v_child_id bigint;
  v_adult_id bigint;
  v_registration_id bigint;
  v_enrollment_id bigint;
  v_contact_id bigint;
  v_guardian_id bigint;
  v_emergency_id bigint;
  v_school_year text;
  v_attendance_days text[];
  v_created_children integer := 0;
  v_enrolled integer := 0;
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  select * into v_submission
  from public.registration_submissions
  where id = p_submission_id
  for update;

  if not found then raise exception 'Submission not found'; end if;
  if v_submission.status = 'approved' then raise exception 'Submission is already approved'; end if;
  if v_submission.status = 'declined' then raise exception 'Declined submissions cannot be approved without reopening them first'; end if;

  select * into v_program from public.programs where id = v_submission.program_id;
  if not found then raise exception 'Program not found'; end if;

  v_payload := v_submission.payload;
  v_guardian := coalesce(v_payload->'guardian', '{}'::jsonb);
  v_emergency := coalesce(v_payload->'emergency', '{}'::jsonb);
  v_school_year := coalesce(nullif(v_program.season_label,''), to_char(current_date,'YYYY'));

  if v_submission.registration_mode = 'adult_short' then
    v_adult := coalesce(v_payload->'adult', '{}'::jsonb);
    if nullif(btrim(v_adult->>'first_name'),'') is null then raise exception 'Adult first name is required'; end if;

    insert into public.adult_participants(first_name,last_name,status,created_by,updated_by)
    values (btrim(v_adult->>'first_name'), nullif(btrim(v_adult->>'last_name'),''), 'active', auth.uid(), auth.uid())
    returning id into v_adult_id;

    insert into public.adult_participant_contacts(participant_id,email,phone,other_phone,address,preferred_contact,emergency_contact_name,emergency_contact_relationship,emergency_contact_phone,created_by,updated_by)
    values (v_adult_id,nullif(btrim(v_adult->>'email'),''),nullif(btrim(v_adult->>'phone'),''),nullif(btrim(v_adult->>'other_phone'),''),nullif(btrim(v_adult->>'address'),''),nullif(btrim(v_adult->>'preferred_contact'),''),nullif(btrim(v_adult->>'emergency_contact_name'),''),nullif(btrim(v_adult->>'emergency_contact_relationship'),''),nullif(btrim(v_adult->>'emergency_contact_phone'),''),auth.uid(),auth.uid());

    insert into public.program_enrollments(program_id,adult_participant_id,status,source,created_by,updated_by)
    values (v_program.id,v_adult_id,'enrolled','parent',auth.uid(),auth.uid())
    returning id into v_enrollment_id;
    v_enrolled := v_enrolled + 1;

    for v_consent in select value from jsonb_array_elements(coalesce(v_payload->'consents','[]'::jsonb)) loop
      insert into public.program_consent_acceptances(program_id,enrollment_id,submission_id,adult_participant_id,consent_id,consent_title,consent_body,required,agreed,signature_name,signature_date,created_by)
      values (v_program.id,v_enrollment_id,v_submission.id,v_adult_id,nullif(v_consent->>'id','')::bigint,coalesce(v_consent->>'title','Consent'),coalesce(v_consent->>'body',''),coalesce((v_consent->>'required')::boolean,false),coalesce((v_consent->>'agreed')::boolean,false),nullif(v_payload->>'signature_name',''),nullif(v_payload->>'signature_date','')::date,auth.uid());
    end loop;
  else
    v_household_id := v_submission.household_id;

    if v_household_id is null then
      insert into public.households(display_name,status,last_program_activity_on,created_by,updated_by)
      values (coalesce(nullif(btrim(v_payload->>'household_display_name'),''), nullif(btrim(v_guardian->>'name'),''), 'New Household'), 'active', current_date, auth.uid(), auth.uid())
      returning id into v_household_id;
    else
      update public.households set last_program_activity_on = current_date where id = v_household_id;
    end if;

    if nullif(btrim(v_guardian->>'name'),'') is not null then
      select id into v_contact_id from public.household_contacts where household_id=v_household_id and active and is_primary order by id limit 1;
      if v_contact_id is null then
        insert into public.household_contacts(household_id,name,relationship,email,phone,other_phone,address,preferred_contact,is_primary,active,created_by,updated_by)
        values (v_household_id,btrim(v_guardian->>'name'),nullif(btrim(v_guardian->>'relationship'),''),nullif(btrim(v_guardian->>'email'),''),nullif(btrim(v_guardian->>'phone'),''),nullif(btrim(v_guardian->>'other_phone'),''),nullif(btrim(v_guardian->>'address'),''),nullif(btrim(v_guardian->>'preferred_contact'),''),true,true,auth.uid(),auth.uid());
      else
        update public.household_contacts set name=btrim(v_guardian->>'name'),relationship=nullif(btrim(v_guardian->>'relationship'),''),email=nullif(btrim(v_guardian->>'email'),''),phone=nullif(btrim(v_guardian->>'phone'),''),other_phone=nullif(btrim(v_guardian->>'other_phone'),''),address=nullif(btrim(v_guardian->>'address'),''),preferred_contact=nullif(btrim(v_guardian->>'preferred_contact'),'') where id=v_contact_id;
      end if;
    end if;

    for v_child in select value from jsonb_array_elements(coalesce(v_payload->'children','[]'::jsonb)) loop
      if coalesce((v_child->>'selected')::boolean,true) is false then continue; end if;
      v_child_id := nullif(v_child->>'existing_child_id','')::bigint;

      if v_child_id is null then
        if nullif(btrim(v_child->>'first_name'),'') is null then raise exception 'Child first name is required'; end if;
        insert into public.children(first_name,last_name,active)
        values (btrim(v_child->>'first_name'),nullif(btrim(v_child->>'last_name'),''),true)
        returning id into v_child_id;
        v_created_children := v_created_children + 1;
      end if;

      insert into public.household_children(household_id,child_id,is_primary,active,created_by)
      values (v_household_id,v_child_id,true,true,auth.uid())
      on conflict (household_id,child_id) do update set active=true,removed_at=null;

      select id into v_registration_id from public.child_registrations where child_id=v_child_id and school_year=v_school_year;
      if v_child ? 'attendance_days' then
        select coalesce(array_agg(value::text order by ord),array[]::text[]) into v_attendance_days
        from jsonb_array_elements_text(coalesce(v_child->'attendance_days','[]'::jsonb)) with ordinality as x(value,ord);
      else
        v_attendance_days := null;
      end if;

      if v_registration_id is null then
        insert into public.child_registrations(child_id,school_year,birth_date,school,grade,status,show_birthday_publicly,attendance_days,attends_other_program,other_program_arrival_notes,dismissal_plan,dismissal_notes,created_by,updated_by)
        values (v_child_id,v_school_year,nullif(v_child->>'birth_date','')::date,nullif(btrim(v_child->>'school'),''),nullif(btrim(v_child->>'grade'),''),'active',coalesce((v_child->>'show_birthday_publicly')::boolean,false),coalesce(v_attendance_days,array[]::text[]),coalesce((v_child->>'attends_other_program')::boolean,false),nullif(btrim(v_child->>'other_program_arrival_notes'),''),nullif(btrim(v_child->>'dismissal_plan'),''),nullif(btrim(v_child->>'dismissal_notes'),''),auth.uid(),auth.uid())
        returning id into v_registration_id;
      else
        update public.child_registrations set
          birth_date=coalesce(nullif(v_child->>'birth_date','')::date,birth_date),
          school=case when v_child ? 'school' then nullif(btrim(v_child->>'school'),'') else school end,
          grade=case when v_child ? 'grade' then nullif(btrim(v_child->>'grade'),'') else grade end,
          status='active',
          attendance_days=coalesce(v_attendance_days,attendance_days),
          attends_other_program=case when v_child ? 'attends_other_program' then coalesce((v_child->>'attends_other_program')::boolean,false) else attends_other_program end,
          other_program_arrival_notes=case when v_child ? 'other_program_arrival_notes' then nullif(btrim(v_child->>'other_program_arrival_notes'),'') else other_program_arrival_notes end,
          dismissal_plan=case when v_child ? 'dismissal_plan' then nullif(btrim(v_child->>'dismissal_plan'),'') else dismissal_plan end,
          dismissal_notes=case when v_child ? 'dismissal_notes' then nullif(btrim(v_child->>'dismissal_notes'),'') else dismissal_notes end
        where id=v_registration_id;
      end if;

      if nullif(btrim(v_guardian->>'name'),'') is not null then
        select id into v_guardian_id from public.child_guardians where registration_id=v_registration_id and is_primary order by id limit 1;
        if v_guardian_id is null then
          insert into public.child_guardians(registration_id,name,relationship,phone,email,is_primary,is_emergency,authorized_pickup,secondary_phone,address,preferred_contact,created_by,updated_by)
          values (v_registration_id,btrim(v_guardian->>'name'),nullif(btrim(v_guardian->>'relationship'),''),nullif(btrim(v_guardian->>'phone'),''),nullif(btrim(v_guardian->>'email'),''),true,false,true,nullif(btrim(v_guardian->>'other_phone'),''),nullif(btrim(v_guardian->>'address'),''),nullif(btrim(v_guardian->>'preferred_contact'),''),auth.uid(),auth.uid());
        else
          update public.child_guardians set name=btrim(v_guardian->>'name'),relationship=nullif(btrim(v_guardian->>'relationship'),''),phone=nullif(btrim(v_guardian->>'phone'),''),email=nullif(btrim(v_guardian->>'email'),''),secondary_phone=nullif(btrim(v_guardian->>'other_phone'),''),address=nullif(btrim(v_guardian->>'address'),''),preferred_contact=nullif(btrim(v_guardian->>'preferred_contact'),'') where id=v_guardian_id;
        end if;
      end if;

      if nullif(btrim(v_emergency->>'name'),'') is not null then
        select id into v_emergency_id from public.child_guardians where registration_id=v_registration_id and is_emergency and not is_primary order by id limit 1;
        if v_emergency_id is null then
          insert into public.child_guardians(registration_id,name,relationship,phone,is_primary,is_emergency,authorized_pickup,created_by,updated_by)
          values (v_registration_id,btrim(v_emergency->>'name'),nullif(btrim(v_emergency->>'relationship'),''),nullif(btrim(v_emergency->>'phone'),''),false,true,false,auth.uid(),auth.uid());
        else
          update public.child_guardians set name=btrim(v_emergency->>'name'),relationship=nullif(btrim(v_emergency->>'relationship'),''),phone=nullif(btrim(v_emergency->>'phone'),'') where id=v_emergency_id;
        end if;
      end if;

      if v_child ? 'allergies' or v_child ? 'medical_conditions' or v_child ? 'learning_support' or v_child ? 'behavioral_support' or v_child ? 'actions_to_take' then
        insert into public.child_health_info(registration_id,allergies,medical_conditions,learning_support,behavioral_support,actions_to_take,important_care_notes,created_by,updated_by)
        values (v_registration_id,nullif(btrim(v_child->>'allergies'),''),nullif(btrim(v_child->>'medical_conditions'),''),nullif(btrim(v_child->>'learning_support'),''),nullif(btrim(v_child->>'behavioral_support'),''),nullif(btrim(v_child->>'actions_to_take'),''),nullif(btrim(v_child->>'important_care_notes'),''),auth.uid(),auth.uid())
        on conflict (registration_id) do update set allergies=excluded.allergies,medical_conditions=excluded.medical_conditions,learning_support=excluded.learning_support,behavioral_support=excluded.behavioral_support,actions_to_take=excluded.actions_to_take,important_care_notes=excluded.important_care_notes;
      end if;

      insert into public.child_registration_agreements(registration_id,info_accuracy_acknowledgment,signature_name,signature_date,terms_version,created_by,updated_by)
      values (v_registration_id,true,nullif(btrim(v_payload->>'signature_name'),''),nullif(v_payload->>'signature_date','')::date,'portal-'||v_program.id::text,auth.uid(),auth.uid())
      on conflict (registration_id) do update set info_accuracy_acknowledgment=true,signature_name=excluded.signature_name,signature_date=excluded.signature_date,terms_version=excluded.terms_version;

      select id into v_enrollment_id from public.program_enrollments where program_id=v_program.id and child_id=v_child_id order by id limit 1;
      if v_enrollment_id is null then
        insert into public.program_enrollments(program_id,household_id,child_id,status,source,created_by,updated_by)
        values (v_program.id,v_household_id,v_child_id,'enrolled','parent',auth.uid(),auth.uid())
        returning id into v_enrollment_id;
      else
        update public.program_enrollments set household_id=v_household_id,status='enrolled',source='parent' where id=v_enrollment_id;
      end if;
      v_enrolled := v_enrolled + 1;

      for v_consent in select value from jsonb_array_elements(coalesce(v_payload->'consents','[]'::jsonb)) loop
        insert into public.program_consent_acceptances(program_id,enrollment_id,submission_id,child_id,consent_id,consent_title,consent_body,required,agreed,signature_name,signature_date,created_by)
        values (v_program.id,v_enrollment_id,v_submission.id,v_child_id,nullif(v_consent->>'id','')::bigint,coalesce(v_consent->>'title','Consent'),coalesce(v_consent->>'body',''),coalesce((v_consent->>'required')::boolean,false),coalesce((v_consent->>'agreed')::boolean,false),nullif(v_payload->>'signature_name',''),nullif(v_payload->>'signature_date','')::date,auth.uid());
      end loop;
    end loop;
  end if;

  update public.registration_submissions
  set status='approved',reviewed_by=auth.uid(),reviewed_at=now()
  where id=v_submission.id;

  if v_submission.access_token_id is not null then
    update public.registration_access_tokens set status='used',used_at=coalesce(used_at,now()) where id=v_submission.access_token_id;
  end if;

  return jsonb_build_object('submission_id',v_submission.id,'household_id',v_household_id,'created_children',v_created_children,'enrollments',v_enrolled);
end;
$$;

revoke all on function public.approve_registration_submission(uuid) from public, anon;
grant execute on function public.approve_registration_submission(uuid) to authenticated;;