-- Simplify Purchasing into collaborative purchase lists + optional budgets.

drop trigger if exists purchase_request_items_editable on public.purchase_request_items;

delete from public.purchase_request_audit
where purchase_request_id in (
  select pr.id
  from public.purchase_requests pr
  join public.budget_accounts b on b.id = pr.budget_id
  where b.name = 'Current Needs'
    and b.period_label = 'Afterschool 26-27'
    and b.allocated_amount = 500
);

delete from public.purchase_requests
where budget_id in (
  select id from public.budget_accounts
  where name = 'Current Needs'
    and period_label = 'Afterschool 26-27'
    and allocated_amount = 500
);

delete from public.budget_accounts
where name = 'Current Needs'
  and period_label = 'Afterschool 26-27'
  and allocated_amount = 500;

alter table public.purchase_requests
  alter column budget_id drop not null;

alter table public.purchase_requests
  add column if not exists title text,
  add column if not exists wishlist_url text;

update public.purchase_requests
set title = coalesce(nullif(btrim(title), ''), coalesce(nullif(btrim(vendor), ''), 'Purchase List'))
where title is null or btrim(title) = '';

alter table public.purchase_requests
  alter column title set default 'Purchase List',
  alter column title set not null;

alter table public.purchase_requests
  drop constraint if exists purchase_requests_title_check;

alter table public.purchase_requests
  add constraint purchase_requests_title_check
  check (char_length(btrim(title)) between 1 and 160);

drop trigger if exists purchase_requests_enforce_transition on public.purchase_requests;

alter table public.purchase_request_items
  add column if not exists vendor text,
  add column if not exists product_url text,
  add column if not exists category_tag text not null default 'Other',
  add column if not exists item_status text not null default 'need',
  add column if not exists purchased_at timestamptz,
  add column if not exists received_at timestamptz;

alter table public.purchase_request_items
  drop constraint if exists purchase_request_items_item_status_check;

alter table public.purchase_request_items
  add constraint purchase_request_items_item_status_check
  check (item_status in ('need','purchased','received'));

create table if not exists public.budget_items (
  id bigint generated by default as identity primary key,
  budget_id bigint not null references public.budget_accounts(id) on update cascade on delete cascade,
  purchase_item_id bigint references public.purchase_request_items(id) on update cascade on delete cascade,
  description text not null check (char_length(btrim(description)) between 1 and 220),
  category text not null default 'Other' check (char_length(btrim(category)) between 1 and 100),
  planned_amount numeric not null default 0 check (planned_amount >= 0),
  counts_toward_plan boolean not null default true,
  notes text,
  active boolean not null default true,
  created_by uuid references public.staff_profiles(user_id) on update cascade on delete set null,
  updated_by uuid references public.staff_profiles(user_id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists budget_items_purchase_item_unique
on public.budget_items(purchase_item_id)
where purchase_item_id is not null;

create index if not exists budget_items_budget_category_idx
on public.budget_items(budget_id, category);

create table if not exists public.budget_spend_entries (
  id bigint generated by default as identity primary key,
  budget_id bigint not null references public.budget_accounts(id) on update cascade on delete cascade,
  budget_item_id bigint references public.budget_items(id) on update cascade on delete set null,
  purchase_item_id bigint references public.purchase_request_items(id) on update cascade on delete cascade,
  description text not null check (char_length(btrim(description)) between 1 and 220),
  category text not null default 'Other' check (char_length(btrim(category)) between 1 and 100),
  amount numeric not null check (amount >= 0),
  spent_on date,
  notes text,
  created_by uuid references public.staff_profiles(user_id) on update cascade on delete set null,
  updated_by uuid references public.staff_profiles(user_id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists budget_spend_entries_purchase_item_unique
on public.budget_spend_entries(purchase_item_id)
where purchase_item_id is not null;

create index if not exists budget_spend_entries_budget_category_idx
on public.budget_spend_entries(budget_id, category);

create index if not exists budget_spend_entries_budget_item_idx
on public.budget_spend_entries(budget_item_id);

create or replace function public.set_simple_finance_audit_fields()
returns trigger
language plpgsql
set search_path = 'public', 'pg_temp'
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := coalesce(new.created_by, auth.uid());
    new.updated_by := coalesce(new.updated_by, auth.uid());
  else
    new.created_by := old.created_by;
    new.updated_by := coalesce(auth.uid(), new.updated_by);
    new.updated_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists budget_items_audit_fields on public.budget_items;
create trigger budget_items_audit_fields
before insert or update on public.budget_items
for each row execute function public.set_simple_finance_audit_fields();

drop trigger if exists budget_spend_entries_audit_fields on public.budget_spend_entries;
create trigger budget_spend_entries_audit_fields
before insert or update on public.budget_spend_entries
for each row execute function public.set_simple_finance_audit_fields();

create or replace function public.set_simple_purchase_actor()
returns trigger
language plpgsql
set search_path = 'public', 'pg_temp'
as $$
begin
  if tg_op = 'INSERT' then
    new.requested_by := coalesce(auth.uid(), new.requested_by);
    new.updated_by := coalesce(auth.uid(), new.updated_by);
  else
    new.requested_by := old.requested_by;
    new.updated_by := coalesce(auth.uid(), new.updated_by);
  end if;
  return new;
end;
$$;

drop trigger if exists purchase_requests_simple_actor on public.purchase_requests;
create trigger purchase_requests_simple_actor
before insert or update on public.purchase_requests
for each row execute function public.set_simple_purchase_actor();

create or replace function public.set_purchase_item_simple_timestamps()
returns trigger
language plpgsql
set search_path = 'public', 'pg_temp'
as $$
begin
  if new.item_status = 'need' then
    new.purchased_at := null;
    new.received_at := null;
  elsif new.item_status = 'purchased' then
    new.purchased_at := coalesce(new.purchased_at, now());
    new.received_at := null;
  elsif new.item_status = 'received' then
    new.purchased_at := coalesce(new.purchased_at, now());
    new.received_at := coalesce(new.received_at, now());
  end if;
  return new;
end;
$$;

drop trigger if exists purchase_request_items_simple_timestamps on public.purchase_request_items;
create trigger purchase_request_items_simple_timestamps
before insert or update of item_status on public.purchase_request_items
for each row execute function public.set_purchase_item_simple_timestamps();

create or replace function public.sync_purchase_item_budget()
returns trigger
language plpgsql
set search_path = 'public', 'pg_temp'
as $$
declare
  v_budget_id bigint;
  v_budget_item_id bigint;
begin
  select budget_id into v_budget_id
  from public.purchase_requests
  where id = new.purchase_request_id;

  if v_budget_id is null then
    delete from public.budget_spend_entries where purchase_item_id = new.id;
    delete from public.budget_items where purchase_item_id = new.id;
    return new;
  end if;

  insert into public.budget_items(
    budget_id, purchase_item_id, description, category, planned_amount,
    counts_toward_plan, notes, active, created_by, updated_by
  )
  values (
    v_budget_id, new.id, new.description, coalesce(nullif(btrim(new.category_tag), ''), 'Other'),
    new.quantity * new.estimated_unit_cost, true, new.notes, true, auth.uid(), auth.uid()
  )
  on conflict (purchase_item_id) where purchase_item_id is not null
  do update set
    budget_id = excluded.budget_id,
    description = excluded.description,
    category = excluded.category,
    planned_amount = excluded.planned_amount,
    notes = excluded.notes,
    active = true,
    updated_by = auth.uid()
  returning id into v_budget_item_id;

  if new.item_status in ('purchased','received') then
    insert into public.budget_spend_entries(
      budget_id, budget_item_id, purchase_item_id, description, category,
      amount, spent_on, notes, created_by, updated_by
    )
    values (
      v_budget_id, v_budget_item_id, new.id, new.description,
      coalesce(nullif(btrim(new.category_tag), ''), 'Other'),
      new.quantity * coalesce(new.actual_unit_cost, new.estimated_unit_cost),
      coalesce(new.purchased_at::date, current_date),
      new.notes, auth.uid(), auth.uid()
    )
    on conflict (purchase_item_id) where purchase_item_id is not null
    do update set
      budget_id = excluded.budget_id,
      budget_item_id = excluded.budget_item_id,
      description = excluded.description,
      category = excluded.category,
      amount = excluded.amount,
      spent_on = excluded.spent_on,
      notes = excluded.notes,
      updated_by = auth.uid();
  else
    delete from public.budget_spend_entries where purchase_item_id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists purchase_request_items_sync_budget on public.purchase_request_items;
create trigger purchase_request_items_sync_budget
after insert or update of purchase_request_id, description, quantity, estimated_unit_cost, actual_unit_cost, category_tag, item_status, notes
on public.purchase_request_items
for each row execute function public.sync_purchase_item_budget();

create or replace function public.resync_purchase_list_budget()
returns trigger
language plpgsql
set search_path = 'public', 'pg_temp'
as $$
begin
  if new.budget_id is distinct from old.budget_id then
    update public.purchase_request_items
    set updated_at = now()
    where purchase_request_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists purchase_requests_resync_budget on public.purchase_requests;
create trigger purchase_requests_resync_budget
after update of budget_id on public.purchase_requests
for each row execute function public.resync_purchase_list_budget();

create or replace view public.budget_simple_summary
with (security_invoker = true)
as
select
  b.id as budget_id,
  b.allocated_amount,
  coalesce((
    select sum(i.planned_amount)
    from public.budget_items i
    where i.budget_id = b.id and i.active and i.counts_toward_plan
  ), 0)::numeric as planned_amount,
  coalesce((
    select sum(s.amount)
    from public.budget_spend_entries s
    where s.budget_id = b.id
  ), 0)::numeric as spent_amount,
  (b.allocated_amount - coalesce((
    select sum(s.amount)
    from public.budget_spend_entries s
    where s.budget_id = b.id
  ), 0))::numeric as remaining_amount
from public.budget_accounts b;

alter table public.budget_items enable row level security;
alter table public.budget_spend_entries enable row level security;

revoke all on public.budget_items from anon;
revoke all on public.budget_spend_entries from anon;
grant select, insert, update, delete on public.budget_items to authenticated;
grant select, insert, update, delete on public.budget_spend_entries to authenticated;
grant usage, select on sequence public.budget_items_id_seq to authenticated;
grant usage, select on sequence public.budget_spend_entries_id_seq to authenticated;
grant select on public.budget_simple_summary to authenticated;

drop policy if exists "admins can view budgets" on public.budget_accounts;
drop policy if exists "active staff can view budgets" on public.budget_accounts;
create policy "active staff can view budgets"
on public.budget_accounts for select to authenticated
using ((select public.current_user_is_active_staff()));

drop policy if exists "admins can view purchase requests" on public.purchase_requests;
drop policy if exists "admins can insert purchase requests" on public.purchase_requests;
drop policy if exists "admins can update purchase requests" on public.purchase_requests;
drop policy if exists "active staff can view purchase lists" on public.purchase_requests;
drop policy if exists "active staff can create purchase lists" on public.purchase_requests;
drop policy if exists "active staff can update purchase lists" on public.purchase_requests;

create policy "active staff can view purchase lists"
on public.purchase_requests for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can create purchase lists"
on public.purchase_requests for insert to authenticated
with check (
  (select public.current_user_is_active_staff())
  and requested_by = (select auth.uid())
);

create policy "active staff can update purchase lists"
on public.purchase_requests for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

drop policy if exists "admins can view purchase request items" on public.purchase_request_items;
drop policy if exists "admins can insert purchase request items" on public.purchase_request_items;
drop policy if exists "admins can update purchase request items" on public.purchase_request_items;
drop policy if exists "admins can delete purchase request items" on public.purchase_request_items;
drop policy if exists "active staff can view purchase items" on public.purchase_request_items;
drop policy if exists "active staff can create purchase items" on public.purchase_request_items;
drop policy if exists "active staff can update purchase items" on public.purchase_request_items;
drop policy if exists "active staff can delete purchase items" on public.purchase_request_items;

create policy "active staff can view purchase items"
on public.purchase_request_items for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can create purchase items"
on public.purchase_request_items for insert to authenticated
with check ((select public.current_user_is_active_staff()));

create policy "active staff can update purchase items"
on public.purchase_request_items for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

create policy "active staff can delete purchase items"
on public.purchase_request_items for delete to authenticated
using ((select public.current_user_is_active_staff()));

drop policy if exists "active staff can view budget items" on public.budget_items;
drop policy if exists "active staff can add budget items" on public.budget_items;
drop policy if exists "active staff can update budget items" on public.budget_items;
drop policy if exists "admins can delete budget items" on public.budget_items;

create policy "active staff can view budget items"
on public.budget_items for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can add budget items"
on public.budget_items for insert to authenticated
with check ((select public.current_user_is_active_staff()));

create policy "active staff can update budget items"
on public.budget_items for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

create policy "admins can delete budget items"
on public.budget_items for delete to authenticated
using (
  (select public.current_user_is_admin())
  or (
    (select public.current_user_is_active_staff())
    and purchase_item_id is not null
  )
);

drop policy if exists "active staff can view budget spending" on public.budget_spend_entries;
drop policy if exists "active staff can add budget spending" on public.budget_spend_entries;
drop policy if exists "active staff can update budget spending" on public.budget_spend_entries;
drop policy if exists "admins can delete budget spending" on public.budget_spend_entries;

create policy "active staff can view budget spending"
on public.budget_spend_entries for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can add budget spending"
on public.budget_spend_entries for insert to authenticated
with check ((select public.current_user_is_active_staff()));

create policy "active staff can update budget spending"
on public.budget_spend_entries for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

create policy "admins can delete budget spending"
on public.budget_spend_entries for delete to authenticated
using (
  (select public.current_user_is_admin())
  or (
    (select public.current_user_is_active_staff())
    and purchase_item_id is not null
  )
);

do $$
declare
  v_budget_id bigint;
  v_uid uuid := '04c30fcc-ee89-42c8-9d54-27bc93130a68'::uuid;
begin
  insert into public.budget_accounts(
    name, period_label, starts_on, ends_on, allocated_amount, notes, active, created_by, updated_by
  )
  values (
    'Summer 2026',
    'Summer 2026',
    '2026-07-13',
    '2026-08-21',
    12800,
    'Imported from Budget Crunching.xlsx. Original planning workbook used for Summer 2026 supervisor budgeting.',
    true,
    v_uid,
    v_uid
  )
  returning id into v_budget_id;

  insert into public.budget_items(
    budget_id, description, category, planned_amount, counts_toward_plan, notes, created_by, updated_by
  ) values
    (v_budget_id,'Ryan','Personnel',500,true,'Original sheet: $20/hr, 5 hr/wk, 8 weeks. Spreadsheet formula calculated $500; note in sheet said $460 total.',v_uid,v_uid),
    (v_budget_id,'Darley','Personnel',2400,true,'Original sheet: $15/hr, 20 hr/wk, 8 weeks.',v_uid,v_uid),
    (v_budget_id,'Betty','Rewards',105.95,true,'Original Money Moves entry; marked Received.',v_uid,v_uid),
    (v_budget_id,'Iris Maker Space','Supplies',624,true,'Imported planned amount.',v_uid,v_uid),
    (v_budget_id,'Amazon','Supplies',2000,true,'General Amazon / center supply allowance.',v_uid,v_uid),
    (v_budget_id,'Snacks','Snacks & Food',1000,true,'Summer snack allowance.',v_uid,v_uid),
    (v_budget_id,'Boda Borg','Field Trips',450,true,'Summer field trip.',v_uid,v_uid),
    (v_budget_id,'LaserMaxx Danvers','Field Trips',505.98,true,'Summer field trip.',v_uid,v_uid),
    (v_budget_id,'Movie day + gift card summer rewards','Rewards',292.61,true,'Summer rewards activity.',v_uid,v_uid),
    (v_budget_id,'Wallgreens Supplies + Intern gas money for field trip transportation','Transportation & Supplies',69.58,true,'Supplies and intern transportation reimbursement.',v_uid,v_uid),
    (v_budget_id,'Kimball Farms Ice Cream for Kids','Field Trips',59.50,true,'Kimball Farms outing.',v_uid,v_uid),
    (v_budget_id,'Kimball Farms Tickets','Field Trips',308,true,'Kimball Farms outing.',v_uid,v_uid),
    (v_budget_id,'Junie + Marcel + Ermeyas Bonuses','Personnel',2000,true,'Summer staff bonuses.',v_uid,v_uid),
    (v_budget_id,'Ermeyas Out of Pocket Expenses','Reimbursements',248.40,false,'The original sheet listed $248.40 on a row that was outside its SUM(E1:E13) planned-total formula, so it is preserved without changing the original planned total.',v_uid,v_uid),
    (v_budget_id,'Printer','Equipment',0,false,'Listed in the original plan without a price.',v_uid,v_uid);

  insert into public.budget_spend_entries(
    budget_id,budget_item_id,description,category,amount,spent_on,notes,created_by,updated_by
  ) values
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Amazon'),'Water Week Amazon Order + Center Needs','Supplies',569.45,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Iris Maker Space'),'Maker''s Space supplies','Supplies',627.53,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Betty'),'Betty Gift Card','Rewards',100,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Darley'),'Darley Total','Personnel',2595,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Ryan'),'Ryan Total','Personnel',460,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Amazon'),'2nd gal Igloo Jug','Supplies',46.10,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Snacks'),'1st Snack Order + Cleaning supplies','Snacks & Food',175.71,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Snacks'),'2nd Snack Order','Snacks & Food',234.95,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Amazon'),'2 Item Amazon Order (Name tags, Cart)','Supplies',105.96,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,null,'Pool Table','Equipment',848.94,null,'Imported from Money Spent; no matching planned line in Money Moves.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Snacks'),'3rd Snack Order','Snacks & Food',183.57,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='LaserMaxx Danvers'),'LaserMaxx','Field Trips',505.98,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Amazon'),'Amazon order','Supplies',139.29,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Snacks'),'4th Snack Order','Snacks & Food',164.73,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Boda Borg'),'Boda Borg','Field Trips',450,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Ermeyas Out of Pocket Expenses'),'Sasha 60 (erm)','Reimbursements',60,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Ermeyas Out of Pocket Expenses'),'Cooking Day Supplies (erm)','Reimbursements',138.02,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Ermeyas Out of Pocket Expenses'),'Dunkin (erm)','Reimbursements',37.38,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Ermeyas Out of Pocket Expenses'),'1 item Amazon order (iron fillings) (erm)','Reimbursements',13.80,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Movie day + gift card summer rewards'),'Movie day + gift card summer rewards','Rewards',292.61,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Wallgreens Supplies + Intern gas money for field trip transportation'),'Wallgreens Supplies + Intern gas money for field trip transportation','Transportation & Supplies',69.58,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Kimball Farms Ice Cream for Kids'),'Kimball Farms Ice Cream for Kids','Field Trips',59.50,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Kimball Farms Tickets'),'Kimball Farms Tickets','Field Trips',308,null,'Imported from Money Spent.',v_uid,v_uid),
    (v_budget_id,(select id from public.budget_items where budget_id=v_budget_id and description='Junie + Marcel + Ermeyas Bonuses'),'Junie + Marcel + Ermeyas Bonuses','Personnel',2000,null,'Imported from Money Spent.',v_uid,v_uid);
end $$;
