create table if not exists public.wheel_stock (
  id bigint generated by default as identity primary key,
  prize_id bigint not null unique references public.wheel_prizes(id) on delete cascade,
  quantity_start integer not null check (quantity_start >= 0),
  quantity_remaining integer not null check (quantity_remaining >= 0 and quantity_remaining <= quantity_start),
  weight numeric not null check (weight > 0),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.wheel_stock(prize_id, quantity_start, quantity_remaining, weight, enabled)
select distinct on (i.prize_id)
  i.prize_id, i.quantity_start, i.quantity_remaining, i.weight, i.enabled
from public.wheel_inventory i
order by i.prize_id, i.month_start desc
on conflict (prize_id) do nothing;

alter table public.wheel_stock enable row level security;

drop policy if exists wheel_stock_active_staff_read on public.wheel_stock;
create policy wheel_stock_active_staff_read on public.wheel_stock
for select to authenticated
using (public.current_user_is_active_staff());

drop policy if exists wheel_stock_admin_manage on public.wheel_stock;
create policy wheel_stock_admin_manage on public.wheel_stock
for all to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

grant select, insert, update, delete on public.wheel_stock to authenticated;
revoke all on public.wheel_stock from anon;
grant usage, select on sequence public.wheel_stock_id_seq to authenticated;
revoke all on sequence public.wheel_stock_id_seq from anon;

alter table public.prize_wins alter column inventory_month_start drop not null;

create or replace function public.add_reward_prize_with_inventory(
  p_name text,
  p_category_id bigint,
  p_tier_id bigint,
  p_month_start date,
  p_quantity integer,
  p_weight numeric
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prize_id bigint;
  v_name text := btrim(p_name);
begin
  if not public.current_user_is_admin() then raise exception 'Admin access required.'; end if;
  if v_name = '' then raise exception 'Prize name is required.'; end if;
  if p_quantity < 0 then raise exception 'Stock cannot be negative.'; end if;
  if p_weight <= 0 then raise exception 'Weight must be greater than zero.'; end if;

  insert into public.wheel_prizes(category_id, name, required_tier_id, active)
  values (p_category_id, v_name, p_tier_id, true)
  returning id into v_prize_id;

  insert into public.wheel_stock(prize_id, quantity_start, quantity_remaining, weight, enabled)
  values (v_prize_id, p_quantity, p_quantity, p_weight, p_quantity > 0);

  return v_prize_id;
end;
$$;

create or replace function public.get_available_wheel(p_child_id bigint, p_month_start date, p_category_slug text)
returns table(prize_id bigint, prize_name text, weight numeric, quantity_remaining integer, required_tier_slug text, required_tier_name text, unlocked_tier_slug text, unlocked_tier_name text, earned_spins integer, used_spins integer, remaining_spins integer)
language plpgsql stable security definer set search_path=public
as $$
declare
  v_earned integer; v_used integer; v_unlocked_min integer; v_unlocked_slug text; v_unlocked_name text;
begin
  if not public.current_user_is_active_staff() then raise exception 'Not authorized'; end if;
  v_earned := public.reward_earned_spins(p_child_id, p_month_start);
  select count(*)::integer into v_used from public.prize_wins where child_id=p_child_id and month_start=date_trunc('month',p_month_start)::date;
  select min_spins,slug,name into v_unlocked_min,v_unlocked_slug,v_unlocked_name from public.wheel_tiers where active and min_spins<=v_earned order by min_spins desc limit 1;
  if coalesce(v_earned-v_used,0)<=0 or v_unlocked_min is null then return; end if;
  return query
  select p.id,p.name,s.weight,s.quantity_remaining,rt.slug,rt.name,v_unlocked_slug,v_unlocked_name,v_earned,v_used,greatest(0,v_earned-v_used)
  from public.wheel_prizes p
  join public.wheel_categories c on c.id=p.category_id and c.slug=p_category_slug and c.active
  join public.wheel_tiers rt on rt.id=p.required_tier_id and rt.active and rt.min_spins<=v_unlocked_min
  join public.wheel_stock s on s.prize_id=p.id
  where p.active and s.enabled and s.quantity_remaining>0 and s.weight>0
  order by rt.min_spins,p.name;
end;
$$;

create or replace function public.spin_monthly_reward_wheel(p_child_id bigint, p_reward_month_start date, p_category_slug text)
returns table(win_id bigint, prize_id bigint, prize_name text, category_name text, tier_name text, earned_spins integer, used_spins integer, remaining_spins integer, quantity_remaining integer, reward_month_start date, inventory_month_start date)
language plpgsql security definer set search_path=public
as $$
declare
  reward_month date:=date_trunc('month',p_reward_month_start)::date;
  e integer; u integer; tid bigint; tname text; tmin integer; cid bigint; cname text;
  sid bigint; pid bigint; pname text; left_qty integer; wid bigint; target_weight numeric; total_weight numeric;
begin
  if not public.current_user_is_active_staff() then raise exception 'Not authorized'; end if;
  perform 1 from public.children c where c.id=p_child_id for update;
  if not found then raise exception 'Child not found'; end if;
  e:=public.reward_earned_spins(p_child_id,reward_month);
  select count(*)::integer into u from public.prize_wins w where w.child_id=p_child_id and w.month_start=reward_month;
  if e<=u then raise exception 'No spins remaining for this reward month'; end if;
  select t.id,t.name,t.min_spins into tid,tname,tmin from public.wheel_tiers t where t.active and t.min_spins<=e order by t.min_spins desc limit 1;
  select c.id,c.name into cid,cname from public.wheel_categories c where c.slug=p_category_slug and c.active;
  if tid is null or cid is null then raise exception 'Wheel unavailable'; end if;
  select sum(s.weight) into total_weight from public.wheel_stock s join public.wheel_prizes p on p.id=s.prize_id join public.wheel_tiers t on t.id=p.required_tier_id where p.active and p.category_id=cid and t.active and t.min_spins<=tmin and s.enabled and s.quantity_remaining>0;
  if coalesce(total_weight,0)<=0 then raise exception 'No in-stock prizes are available on this wheel'; end if;
  target_weight:=random()*total_weight;
  with q as (
    select s.id as stock_key,p.id as prize_key,p.name as prize_label,sum(s.weight) over(order by p.id) as running_weight
    from public.wheel_stock s join public.wheel_prizes p on p.id=s.prize_id join public.wheel_tiers t on t.id=p.required_tier_id
    where p.active and p.category_id=cid and t.active and t.min_spins<=tmin and s.enabled and s.quantity_remaining>0
  ) select q.stock_key,q.prize_key,q.prize_label into sid,pid,pname from q where q.running_weight>target_weight order by q.running_weight limit 1;
  update public.wheel_stock s set quantity_remaining=s.quantity_remaining-1,updated_at=now() where s.id=sid and s.quantity_remaining>0 returning s.quantity_remaining into left_qty;
  if not found then raise exception 'Prize stock changed; please spin again'; end if;
  insert into public.prize_wins(child_id,month_start,inventory_month_start,category_id,tier_id,prize_id,spin_number,earned_spins_snapshot,prize_name_snapshot,category_name_snapshot,tier_name_snapshot,recorded_by)
  values(p_child_id,reward_month,null,cid,tid,pid,u+1,e,pname,cname,tname,auth.uid()) returning id into wid;
  return query select wid,pid,pname,cname,tname,e,u+1,greatest(0,e-u-1),left_qty,reward_month,null::date;
end;
$$;

create or replace function public.spin_monthly_reward_wheel(p_child_id bigint, p_reward_month_start date, p_inventory_month_start date, p_category_slug text)
returns table(win_id bigint, prize_id bigint, prize_name text, category_name text, tier_name text, earned_spins integer, used_spins integer, remaining_spins integer, quantity_remaining integer, reward_month_start date, inventory_month_start date)
language sql security definer set search_path=public
as $$
  select * from public.spin_monthly_reward_wheel(p_child_id,p_reward_month_start,p_category_slug);
$$;

create or replace function public.spin_reward_wheel(p_child_id bigint, p_month_start date, p_category_slug text)
returns table(win_id bigint, prize_id bigint, prize_name text, category_name text, tier_name text, earned_spins integer, used_spins integer, remaining_spins integer, quantity_remaining integer)
language sql security definer set search_path=public
as $$
  select win_id,prize_id,prize_name,category_name,tier_name,earned_spins,used_spins,remaining_spins,quantity_remaining
  from public.spin_monthly_reward_wheel(p_child_id,p_month_start,p_category_slug);
$$;

create or replace function public.get_available_free_wheel(p_month_start date, p_category_slug text, p_tier_slug text)
returns table(inventory_id bigint, prize_id bigint, prize_name text, required_tier_name text, weight numeric, quantity_remaining integer)
language plpgsql stable security definer set search_path=public
as $$
declare cid bigint; selected_tier_min integer;
begin
  if not public.current_user_is_active_staff() then raise exception 'Not authorized'; end if;
  select c.id into cid from public.wheel_categories c where c.slug=p_category_slug and c.active;
  select t.min_spins into selected_tier_min from public.wheel_tiers t where t.slug=p_tier_slug and t.active;
  if cid is null or selected_tier_min is null then raise exception 'Wheel unavailable'; end if;
  return query
  select s.id,p.id,p.name,rt.name,s.weight,s.quantity_remaining
  from public.wheel_stock s
  join public.wheel_prizes p on p.id=s.prize_id
  join public.wheel_tiers rt on rt.id=p.required_tier_id
  where p.active and p.category_id=cid and rt.active and rt.min_spins<=selected_tier_min and s.enabled and s.quantity_remaining>0 and s.weight>0
  order by p.id;
end;
$$;

create or replace function public.spin_free_reward_wheel(p_child_id bigint,p_month_start date,p_category_slug text,p_tier_slug text,p_reason text default null)
returns table(win_id bigint, prize_id bigint, prize_name text, category_name text, tier_name text, quantity_remaining integer, won_at timestamptz)
language plpgsql security definer set search_path=public
as $$
declare
  m date:=date_trunc('month',p_month_start)::date; cid bigint; cname text; tid bigint; tname text; tmin integer;
  sid bigint; pid bigint; pname text; left_qty integer; wid bigint; won_time timestamptz; target_weight numeric; total_weight numeric;
begin
  if not public.current_user_is_active_staff() then raise exception 'Not authorized'; end if;
  perform 1 from public.children c where c.id=p_child_id for update;
  if not found then raise exception 'Child not found'; end if;
  select c.id,c.name into cid,cname from public.wheel_categories c where c.slug=p_category_slug and c.active;
  select t.id,t.name,t.min_spins into tid,tname,tmin from public.wheel_tiers t where t.slug=p_tier_slug and t.active;
  if cid is null or tid is null then raise exception 'Wheel unavailable'; end if;
  select sum(s.weight) into total_weight from public.wheel_stock s join public.wheel_prizes p on p.id=s.prize_id join public.wheel_tiers rt on rt.id=p.required_tier_id where p.active and p.category_id=cid and rt.active and rt.min_spins<=tmin and s.enabled and s.quantity_remaining>0 and s.weight>0;
  if coalesce(total_weight,0)<=0 then raise exception 'No in-stock prizes are available on this wheel'; end if;
  target_weight:=random()*total_weight;
  with q as (
    select s.id as stock_key,p.id as prize_key,p.name as prize_label,sum(s.weight) over(order by p.id) as running_weight
    from public.wheel_stock s join public.wheel_prizes p on p.id=s.prize_id join public.wheel_tiers rt on rt.id=p.required_tier_id
    where p.active and p.category_id=cid and rt.active and rt.min_spins<=tmin and s.enabled and s.quantity_remaining>0 and s.weight>0
  ) select q.stock_key,q.prize_key,q.prize_label into sid,pid,pname from q where q.running_weight>target_weight order by q.running_weight limit 1;
  update public.wheel_stock s set quantity_remaining=s.quantity_remaining-1,updated_at=now() where s.id=sid and s.quantity_remaining>0 returning s.quantity_remaining into left_qty;
  if not found then raise exception 'Prize stock changed; please spin again'; end if;
  insert into public.free_prize_wins(child_id,month_start,category_id,tier_id,prize_id,prize_name_snapshot,category_name_snapshot,tier_name_snapshot,reason,recorded_by)
  values(p_child_id,m,cid,tid,pid,pname,cname,tname,nullif(trim(coalesce(p_reason,'')),''),auth.uid()) returning id,public.free_prize_wins.won_at into wid,won_time;
  return query select wid,pid,pname,cname,tname,left_qty,won_time;
end;
$$;

grant execute on function public.spin_monthly_reward_wheel(bigint,date,text) to authenticated;
grant execute on function public.spin_monthly_reward_wheel(bigint,date,date,text) to authenticated;
revoke all on function public.spin_monthly_reward_wheel(bigint,date,text) from anon;
revoke all on function public.spin_monthly_reward_wheel(bigint,date,date,text) from anon;;