create table if not exists public.center_announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) > 0),
  body text not null check (char_length(btrim(body)) > 0),
  pinned boolean not null default false,
  active boolean not null default true,
  starts_on date not null default current_date,
  ends_on date,
  created_by uuid not null references public.staff_profiles(user_id),
  updated_by uuid not null references public.staff_profiles(user_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint center_announcements_date_range_check check (ends_on is null or ends_on >= starts_on)
);

alter table public.center_announcements enable row level security;
grant select, insert, update on public.center_announcements to authenticated;
grant usage, select on sequence public.center_announcements_id_seq to authenticated;

drop policy if exists "active staff can view announcements" on public.center_announcements;
create policy "active staff can view announcements" on public.center_announcements for select to authenticated using ((select public.current_user_is_active_staff()));
drop policy if exists "active staff can create announcements" on public.center_announcements;
create policy "active staff can create announcements" on public.center_announcements for insert to authenticated with check ((select public.current_user_is_active_staff()) and created_by = (select auth.uid()) and updated_by = (select auth.uid()));
drop policy if exists "active staff can update announcements" on public.center_announcements;
create policy "active staff can update announcements" on public.center_announcements for update to authenticated using ((select public.current_user_is_active_staff())) with check ((select public.current_user_is_active_staff()));

drop trigger if exists center_announcements_set_updated_fields on public.center_announcements;
create trigger center_announcements_set_updated_fields before update on public.center_announcements for each row execute function public.set_center_record_updated_fields();
create index if not exists center_announcements_active_dates_idx on public.center_announcements (active, starts_on, ends_on);

create table if not exists public.inventory_restock_requests (
  item_id bigint primary key references public.inventory_items(id) on delete cascade,
  requested_by uuid not null references public.staff_profiles(user_id),
  requested_at timestamptz not null default now()
);

alter table public.inventory_restock_requests enable row level security;
grant select, insert, delete on public.inventory_restock_requests to authenticated;

drop policy if exists "active staff can view restock requests" on public.inventory_restock_requests;
create policy "active staff can view restock requests" on public.inventory_restock_requests for select to authenticated using ((select public.current_user_is_active_staff()));
drop policy if exists "active staff can request restock" on public.inventory_restock_requests;
create policy "active staff can request restock" on public.inventory_restock_requests for insert to authenticated with check ((select public.current_user_is_active_staff()) and requested_by = (select auth.uid()));
drop policy if exists "active staff can clear restock request" on public.inventory_restock_requests;
create policy "active staff can clear restock request" on public.inventory_restock_requests for delete to authenticated using ((select public.current_user_is_active_staff()));
create index if not exists inventory_restock_requests_requested_at_idx on public.inventory_restock_requests (requested_at desc);
