create table public.calendar_events (
  id bigint generated by default as identity primary key,
  event_date date not null,
  title text not null check (length(btrim(title)) between 1 and 120),
  event_type text not null default 'activity' check (event_type in ('activity','field_trip','club','program','meeting','closure','special_event','other')),
  description text,
  staff_notes text,
  location text,
  all_day boolean not null default false,
  start_time time without time zone,
  end_time time without time zone,
  visibility text not null default 'public' check (visibility in ('public','staff')),
  status text not null default 'scheduled' check (status in ('scheduled','canceled')),
  series_id uuid,
  created_by uuid not null references auth.users(id),
  canceled_by uuid references auth.users(id),
  canceled_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint calendar_event_time_order check (end_time is null or start_time is null or end_time > start_time),
  constraint calendar_event_cancel_state check (
    (status = 'scheduled' and canceled_at is null and canceled_by is null)
    or status = 'canceled'
  )
);

alter table public.calendar_events enable row level security;

grant select, insert, update on public.calendar_events to authenticated;
grant usage, select on sequence public.calendar_events_id_seq to authenticated;

create policy "active staff can view calendar events"
on public.calendar_events
for select
to authenticated
using ((select public.current_user_is_active_staff()));

create policy "admins can add calendar events"
on public.calendar_events
for insert
to authenticated
with check (
  (select public.current_user_is_admin())
  and created_by = (select auth.uid())
);

create policy "admins can update calendar events"
on public.calendar_events
for update
to authenticated
using ((select public.current_user_is_admin()))
with check ((select public.current_user_is_admin()));

create index calendar_events_date_idx
  on public.calendar_events(event_date);
create index calendar_events_date_status_idx
  on public.calendar_events(event_date, status);
create index calendar_events_public_date_idx
  on public.calendar_events(event_date, visibility, status);
create index calendar_events_series_idx
  on public.calendar_events(series_id)
  where series_id is not null;
create index calendar_events_created_by_idx
  on public.calendar_events(created_by);
create index calendar_events_canceled_by_idx
  on public.calendar_events(canceled_by)
  where canceled_by is not null;

create function public.touch_calendar_event_updated_at()
returns trigger
language plpgsql
set search_path = 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger calendar_events_touch_updated_at
before update on public.calendar_events
for each row execute function public.touch_calendar_event_updated_at();

create view public.calendar_public_events
with (security_invoker = true)
as
select
  id,
  event_date,
  title,
  event_type,
  description,
  location,
  all_day,
  start_time,
  end_time,
  status,
  series_id,
  updated_at
from public.calendar_events
where visibility = 'public';

grant select on public.calendar_public_events to authenticated;;