create table if not exists public.learning_homework_tasks (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete cascade,
  week_start date not null,
  due_date date,
  school_subject text not null check (char_length(btrim(school_subject)) between 1 and 80),
  title text not null check (char_length(btrim(title)) between 1 and 180),
  details text,
  estimated_minutes integer check (estimated_minutes is null or (estimated_minutes between 1 and 240)),
  status text not null default 'assigned'
    check (status = any (array['assigned'::text,'awaiting_review'::text,'completed'::text])),
  student_marked_done_at timestamptz,
  staff_verified_at timestamptz,
  staff_verified_by uuid references auth.users(id),
  assigned_by uuid not null references auth.users(id),
  assigned_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  constraint learning_homework_awaiting_check
    check (status <> 'awaiting_review' or student_marked_done_at is not null),
  constraint learning_homework_completed_check
    check (status <> 'completed' or (student_marked_done_at is not null and staff_verified_at is not null and staff_verified_by is not null))
);

create index if not exists learning_homework_tasks_child_week_idx
  on public.learning_homework_tasks(child_id, week_start);
create index if not exists learning_homework_tasks_status_idx
  on public.learning_homework_tasks(status, week_start);

alter table public.learning_homework_tasks enable row level security;

drop policy if exists "active staff can view learning homework" on public.learning_homework_tasks;
create policy "active staff can view learning homework"
on public.learning_homework_tasks for select to authenticated
using ((select public.current_user_is_active_staff()));

drop policy if exists "active staff can add learning homework" on public.learning_homework_tasks;
create policy "active staff can add learning homework"
on public.learning_homework_tasks for insert to authenticated
with check (
  (select public.current_user_is_active_staff())
  and assigned_by = (select auth.uid())
  and updated_by = (select auth.uid())
);

drop policy if exists "active staff can update learning homework" on public.learning_homework_tasks;
create policy "active staff can update learning homework"
on public.learning_homework_tasks for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

drop policy if exists "active staff can remove untouched learning homework" on public.learning_homework_tasks;
create policy "active staff can remove untouched learning homework"
on public.learning_homework_tasks for delete to authenticated
using (
  (select public.current_user_is_active_staff())
  and status = 'assigned'
  and student_marked_done_at is null
);

drop policy if exists "admins can delete learning homework" on public.learning_homework_tasks;
create policy "admins can delete learning homework"
on public.learning_homework_tasks for delete to authenticated
using ((select public.current_user_is_admin()));

grant select, insert, update, delete on public.learning_homework_tasks to authenticated;
grant usage, select on sequence public.learning_homework_tasks_id_seq to authenticated;
