create table public.staff_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'staff' check (role in ('staff','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.children (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.card_rules (
  card text primary key check (card in ('diamond','green','yellow','orange','red')),
  points numeric(4,1) not null,
  display_order smallint not null unique,
  updated_at timestamptz not null default now()
);

insert into public.card_rules (card, points, display_order) values
  ('diamond', 2.0, 1),
  ('green', 1.0, 2),
  ('yellow', -0.5, 3),
  ('orange', -1.0, 4),
  ('red', -2.0, 5);

create table public.behavior_entries (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete restrict,
  entry_date date not null default current_date,
  entry_type text not null check (entry_type in ('behavior','status')),
  card text check (card in ('diamond','green','yellow','orange','red')),
  day_status text check (day_status in ('absent','sick','didnt_report','field_trip','closed','other')),
  points numeric(4,1) not null default 0,
  note text,
  recorded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint behavior_entry_shape check (
    (entry_type = 'behavior' and card is not null and day_status is null)
    or
    (entry_type = 'status' and card is null and day_status is not null)
  ),
  constraint one_daily_entry_per_child unique (child_id, entry_date)
);

create table public.app_settings (
  id smallint primary key default 1 check (id = 1),
  wheel_rule_mode text not null default 'pending' check (wheel_rule_mode in ('pending','points_per_spin','tiers')),
  points_per_spin numeric(6,2),
  wheel_rule_notes text,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id, wheel_rule_mode, wheel_rule_notes)
values (1, 'pending', 'Prize wheel conversion formula has not been confirmed yet.');

create or replace function public.set_behavior_entry_points()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.entry_type = 'behavior' then
    select points into new.points from public.card_rules where card = new.card;
    if new.points is null then
      raise exception 'Unknown behavior card: %', new.card;
    end if;
  else
    new.points := 0;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger behavior_entries_set_points
before insert or update of entry_type, card, day_status
on public.behavior_entries
for each row execute function public.set_behavior_entry_points();

create index behavior_entries_child_date_idx on public.behavior_entries (child_id, entry_date desc);
create index behavior_entries_date_idx on public.behavior_entries (entry_date desc);
create index children_active_idx on public.children (active) where active = true;

alter table public.staff_profiles enable row level security;
alter table public.children enable row level security;
alter table public.card_rules enable row level security;
alter table public.behavior_entries enable row level security;
alter table public.app_settings enable row level security;

revoke all on table public.staff_profiles, public.children, public.card_rules, public.behavior_entries, public.app_settings from anon;
grant select on table public.staff_profiles, public.children, public.card_rules, public.behavior_entries, public.app_settings to authenticated;
grant insert, update on table public.behavior_entries to authenticated;
grant insert, update, delete on table public.children, public.card_rules, public.app_settings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "staff can view own profile"
on public.staff_profiles for select
to authenticated
using (user_id = (select auth.uid()));

create policy "active staff can view children"
on public.children for select
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active
));

create policy "admins can add children"
on public.children for insert
to authenticated
with check (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
));

create policy "admins can update children"
on public.children for update
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
))
with check (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
));

create policy "admins can delete children"
on public.children for delete
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
));

create policy "active staff can view card rules"
on public.card_rules for select
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active
));

create policy "admins can modify card rules"
on public.card_rules for all
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
))
with check (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
));

create policy "active staff can view behavior entries"
on public.behavior_entries for select
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active
));

create policy "active staff can add behavior entries"
on public.behavior_entries for insert
to authenticated
with check (
  recorded_by = (select auth.uid())
  and exists (
    select 1 from public.staff_profiles sp
    where sp.user_id = (select auth.uid()) and sp.active
  )
);

create policy "active staff can correct behavior entries"
on public.behavior_entries for update
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active
))
with check (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active
));

create policy "active staff can view settings"
on public.app_settings for select
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active
));

create policy "admins can modify settings"
on public.app_settings for all
to authenticated
using (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
))
with check (exists (
  select 1 from public.staff_profiles sp
  where sp.user_id = (select auth.uid()) and sp.active and sp.role = 'admin'
));;