
create table if not exists public.learning_progress_report_archives (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children(id) on delete restrict,
  period_start date not null,
  period_end date not null,
  report_title text not null,
  status text not null default 'finalized' check (status in ('finalized','archived')),
  snapshot jsonb not null check (jsonb_typeof(snapshot)='object'),
  finalized_by uuid not null references auth.users(id),
  finalized_at timestamptz not null default now(),
  archived_by uuid references auth.users(id),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint learning_progress_report_archive_period_check check (period_end >= period_start),
  constraint learning_progress_report_archive_status_check check (
    (status='finalized' and archived_by is null and archived_at is null)
    or
    (status='archived' and archived_by is not null and archived_at is not null)
  )
);

create unique index if not exists learning_progress_report_one_finalized_period_idx
  on public.learning_progress_report_archives(child_id,period_start,period_end)
  where status='finalized';

create index if not exists learning_progress_report_archive_child_idx
  on public.learning_progress_report_archives(child_id,finalized_at desc);

alter table public.learning_progress_report_archives enable row level security;

drop policy if exists "active staff can view progress report archives" on public.learning_progress_report_archives;
create policy "active staff can view progress report archives"
on public.learning_progress_report_archives
for select to authenticated
using (public.current_user_is_active_staff());

drop policy if exists "active staff can finalize progress reports" on public.learning_progress_report_archives;
create policy "active staff can finalize progress reports"
on public.learning_progress_report_archives
for insert to authenticated
with check (
  public.current_user_is_active_staff()
  and finalized_by=(select auth.uid())
  and status='finalized'
);

drop policy if exists "active staff can archive progress reports" on public.learning_progress_report_archives;
create policy "active staff can archive progress reports"
on public.learning_progress_report_archives
for update to authenticated
using (public.current_user_is_active_staff())
with check (public.current_user_is_active_staff());

revoke all on public.learning_progress_report_archives from anon;
grant select,insert,update on public.learning_progress_report_archives to authenticated;
grant usage,select on sequence public.learning_progress_report_archives_id_seq to authenticated;

create or replace function public.protect_learning_progress_report_snapshot()
returns trigger
language plpgsql
security invoker
set search_path=public
as $$
begin
  if old.child_id is distinct from new.child_id
     or old.period_start is distinct from new.period_start
     or old.period_end is distinct from new.period_end
     or old.report_title is distinct from new.report_title
     or old.snapshot is distinct from new.snapshot
     or old.finalized_by is distinct from new.finalized_by
     or old.finalized_at is distinct from new.finalized_at then
    raise exception 'Finalized progress report snapshots are immutable';
  end if;

  if old.status='archived' and new.status <> 'archived' then
    raise exception 'Archived progress reports cannot be reopened';
  end if;

  if old.status='finalized' and new.status='archived' then
    if new.archived_by is null or new.archived_at is null then
      raise exception 'Archive metadata is required';
    end if;
  elsif old.status is distinct from new.status then
    raise exception 'Unsupported progress report status change';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists protect_learning_progress_report_snapshot on public.learning_progress_report_archives;
create trigger protect_learning_progress_report_snapshot
before update on public.learning_progress_report_archives
for each row execute function public.protect_learning_progress_report_snapshot();

create or replace function public.finalize_learning_progress_report(
  p_child_id bigint,
  p_period_start date,
  p_period_end date,
  p_report_title text,
  p_snapshot jsonb
)
returns public.learning_progress_report_archives
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_report public.learning_progress_report_archives;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;
  if p_period_end < p_period_start then
    raise exception 'Report end date must be on or after the start date';
  end if;
  if jsonb_typeof(p_snapshot) <> 'object' then
    raise exception 'Report snapshot must be an object';
  end if;
  if exists (
    select 1 from public.learning_progress_report_archives
    where child_id=p_child_id
      and period_start=p_period_start
      and period_end=p_period_end
      and status='finalized'
  ) then
    raise exception 'A finalized report already exists for this student and reporting period. Archive it before finalizing a replacement.';
  end if;

  insert into public.learning_progress_report_archives(
    child_id,period_start,period_end,report_title,status,snapshot,finalized_by
  ) values (
    p_child_id,p_period_start,p_period_end,
    nullif(trim(coalesce(p_report_title,'')),''),
    'finalized',p_snapshot,(select auth.uid())
  )
  returning * into v_report;

  if v_report.report_title is null then
    raise exception 'Report title is required';
  end if;

  return v_report;
end;
$$;

create or replace function public.archive_learning_progress_report(p_report_id bigint)
returns public.learning_progress_report_archives
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_report public.learning_progress_report_archives;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  update public.learning_progress_report_archives
  set status='archived',
      archived_by=(select auth.uid()),
      archived_at=now()
  where id=p_report_id and status='finalized'
  returning * into v_report;

  if v_report.id is null then
    raise exception 'That report is not available to archive';
  end if;
  return v_report;
end;
$$;

revoke all on function public.finalize_learning_progress_report(bigint,date,date,text,jsonb) from public,anon;
grant execute on function public.finalize_learning_progress_report(bigint,date,date,text,jsonb) to authenticated;

revoke all on function public.archive_learning_progress_report(bigint) from public,anon;
grant execute on function public.archive_learning_progress_report(bigint) to authenticated;
;