create table public.attendance_visits (
  id bigint generated by default as identity primary key,
  service_date date not null default current_date,
  participant_type text not null check (participant_type in ('child', 'adult', 'family', 'visitor')),
  child_id bigint references public.children(id) on delete restrict,
  visitor_name text,
  purpose text,
  signed_in_at timestamptz not null default now(),
  signed_out_at timestamptz,
  source text not null default 'staff' check (source in ('kiosk', 'staff', 'manual', 'import')),
  status text not null default 'active' check (status in ('active', 'voided')),
  recorded_by uuid not null references auth.users(id) on delete restrict,
  voided_at timestamptz,
  voided_by uuid references auth.users(id) on delete restrict,
  void_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_visits_participant_shape check (
    (participant_type = 'child' and child_id is not null and visitor_name is null)
    or
    (participant_type in ('adult', 'family', 'visitor') and child_id is null and nullif(btrim(visitor_name), '') is not null)
  ),
  constraint attendance_visits_signout_order check (signed_out_at is null or signed_out_at >= signed_in_at),
  constraint attendance_visits_void_fields check (
    (status = 'active' and voided_at is null and voided_by is null)
    or
    (status = 'voided' and voided_at is not null and voided_by is not null and nullif(btrim(void_reason), '') is not null)
  )
);

create unique index attendance_visits_one_active_child_per_day
  on public.attendance_visits (child_id, service_date)
  where participant_type = 'child' and status = 'active';

create index attendance_visits_service_date_status_idx
  on public.attendance_visits (service_date, status);

create index attendance_visits_child_date_idx
  on public.attendance_visits (child_id, service_date)
  where child_id is not null;

create table public.attendance_wellbeing (
  visit_id bigint primary key references public.attendance_visits(id) on delete restrict,
  mood text not null check (mood in ('good', 'okay', 'hard_day')),
  recorded_by uuid not null references auth.users(id) on delete restrict,
  recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.operating_days (
  service_date date primary key,
  is_open boolean not null default true,
  reason text,
  notes text,
  recorded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index operating_days_open_date_idx
  on public.operating_days (service_date)
  where is_open;

create table public.attendance_audit (
  id bigint generated always as identity primary key,
  visit_id bigint not null,
  action text not null check (action in ('created', 'updated', 'voided', 'mood_updated')),
  old_record jsonb,
  new_record jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index attendance_audit_visit_idx on public.attendance_audit (visit_id, changed_at desc);

alter table public.attendance_visits enable row level security;
alter table public.attendance_wellbeing enable row level security;
alter table public.operating_days enable row level security;
alter table public.attendance_audit enable row level security;

revoke all on public.attendance_visits from anon;
revoke all on public.attendance_wellbeing from anon;
revoke all on public.operating_days from anon;
revoke all on public.attendance_audit from anon;

grant select, insert, update on public.attendance_visits to authenticated;
grant select, insert on public.attendance_wellbeing to authenticated;
grant select, insert, update on public.operating_days to authenticated;
grant select on public.attendance_audit to authenticated;
grant usage, select on sequence public.attendance_visits_id_seq to authenticated;
grant select on sequence public.attendance_audit_id_seq to authenticated;

create policy "active staff can view attendance visits"
on public.attendance_visits for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can add attendance visits"
on public.attendance_visits for insert to authenticated
with check (
  (select public.current_user_is_active_staff())
  and recorded_by = (select auth.uid())
  and status = 'active'
);

create policy "active staff can correct attendance visits"
on public.attendance_visits for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

create policy "active staff can view attendance wellbeing"
on public.attendance_wellbeing for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can add attendance wellbeing"
on public.attendance_wellbeing for insert to authenticated
with check (
  (select public.current_user_is_active_staff())
  and recorded_by = (select auth.uid())
);

create policy "active staff can view operating days"
on public.operating_days for select to authenticated
using ((select public.current_user_is_active_staff()));

create policy "active staff can add operating days"
on public.operating_days for insert to authenticated
with check (
  (select public.current_user_is_active_staff())
  and recorded_by = (select auth.uid())
);

create policy "active staff can update operating days"
on public.operating_days for update to authenticated
using ((select public.current_user_is_active_staff()))
with check ((select public.current_user_is_active_staff()));

create policy "active staff can view attendance audit"
on public.attendance_audit for select to authenticated
using ((select public.current_user_is_active_staff()));

create or replace function public.audit_attendance_visit_changes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text;
begin
  if tg_op = 'INSERT' then
    insert into public.attendance_audit (visit_id, action, old_record, new_record, changed_by)
    values (new.id, 'created', null, to_jsonb(new), auth.uid());
    return new;
  end if;

  v_action := case
    when old.status <> 'voided' and new.status = 'voided' then 'voided'
    else 'updated'
  end;

  insert into public.attendance_audit (visit_id, action, old_record, new_record, changed_by)
  values (new.id, v_action, to_jsonb(old), to_jsonb(new), auth.uid());

  return new;
end;
$$;

revoke execute on function public.audit_attendance_visit_changes() from public, anon, authenticated;

create trigger attendance_visit_audit_trigger
after insert or update on public.attendance_visits
for each row execute function public.audit_attendance_visit_changes();

create or replace function public.sign_in_child(
  p_child_id bigint,
  p_mood text,
  p_service_date date default current_date,
  p_source text default 'kiosk'
)
returns table (visit_id bigint, signed_in_at timestamptz)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_visit_id bigint;
  v_signed_in_at timestamptz;
  v_mood text;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  if p_service_date is null then
    p_service_date := current_date;
  end if;

  if p_source not in ('kiosk', 'staff', 'manual', 'import') then
    raise exception 'Invalid attendance source';
  end if;

  v_mood := case p_mood
    when 'happy' then 'good'
    when 'meh' then 'okay'
    when 'sad' then 'hard_day'
    when 'good' then 'good'
    when 'okay' then 'okay'
    when 'hard_day' then 'hard_day'
    else null
  end;

  if v_mood is null then
    raise exception 'Invalid mood selection';
  end if;

  if not exists (
    select 1 from public.children c where c.id = p_child_id and c.active
  ) then
    raise exception 'Child is not active or could not be found';
  end if;

  insert into public.operating_days (service_date, is_open, reason, recorded_by)
  values (p_service_date, true, 'Sign-in activity recorded', auth.uid())
  on conflict (service_date) do nothing;

  begin
    insert into public.attendance_visits (
      service_date, participant_type, child_id, source, recorded_by
    ) values (
      p_service_date, 'child', p_child_id, p_source, auth.uid()
    )
    returning id, attendance_visits.signed_in_at into v_visit_id, v_signed_in_at;
  exception
    when unique_violation then
      raise exception 'This child is already signed in for this date';
  end;

  insert into public.attendance_wellbeing (visit_id, mood, recorded_by)
  values (v_visit_id, v_mood, auth.uid());

  return query select v_visit_id, v_signed_in_at;
end;
$$;

create or replace function public.sign_in_visitor(
  p_name text,
  p_visitor_type text,
  p_purpose text,
  p_service_date date default current_date,
  p_source text default 'kiosk'
)
returns table (visit_id bigint, signed_in_at timestamptz)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_visit_id bigint;
  v_signed_in_at timestamptz;
  v_type text;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  if nullif(btrim(p_name), '') is null then
    raise exception 'Name or identifier is required';
  end if;

  v_type := lower(btrim(p_visitor_type));
  if v_type not in ('adult', 'family', 'visitor') then
    raise exception 'Invalid visitor type';
  end if;

  if p_service_date is null then
    p_service_date := current_date;
  end if;

  if p_source not in ('kiosk', 'staff', 'manual', 'import') then
    raise exception 'Invalid attendance source';
  end if;

  insert into public.operating_days (service_date, is_open, reason, recorded_by)
  values (p_service_date, true, 'Sign-in activity recorded', auth.uid())
  on conflict (service_date) do nothing;

  insert into public.attendance_visits (
    service_date, participant_type, visitor_name, purpose, source, recorded_by
  ) values (
    p_service_date, v_type, btrim(p_name), nullif(btrim(p_purpose), ''), p_source, auth.uid()
  )
  returning id, attendance_visits.signed_in_at into v_visit_id, v_signed_in_at;

  return query select v_visit_id, v_signed_in_at;
end;
$$;

create or replace function public.sign_out_visitor(p_visit_id bigint)
returns timestamptz
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_time timestamptz := now();
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  update public.attendance_visits
  set signed_out_at = v_time,
      updated_at = v_time
  where id = p_visit_id
    and participant_type <> 'child'
    and status = 'active'
    and signed_out_at is null;

  if not found then
    raise exception 'Active visitor sign-in could not be found';
  end if;

  return v_time;
end;
$$;

create or replace function public.void_attendance_visit(p_visit_id bigint, p_reason text)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  if nullif(btrim(p_reason), '') is null then
    raise exception 'A correction reason is required';
  end if;

  update public.attendance_visits
  set status = 'voided',
      voided_at = now(),
      voided_by = auth.uid(),
      void_reason = btrim(p_reason),
      updated_at = now()
  where id = p_visit_id
    and status = 'active';

  if not found then
    raise exception 'Active attendance record could not be found';
  end if;
end;
$$;

create or replace function public.correct_child_mood(
  p_visit_id bigint,
  p_mood text,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old public.attendance_wellbeing%rowtype;
  v_new public.attendance_wellbeing%rowtype;
  v_mood text;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  if nullif(btrim(p_reason), '') is null then
    raise exception 'A correction reason is required';
  end if;

  v_mood := case p_mood
    when 'happy' then 'good'
    when 'meh' then 'okay'
    when 'sad' then 'hard_day'
    when 'good' then 'good'
    when 'okay' then 'okay'
    when 'hard_day' then 'hard_day'
    else null
  end;

  if v_mood is null then
    raise exception 'Invalid mood selection';
  end if;

  select * into v_old
  from public.attendance_wellbeing
  where visit_id = p_visit_id;

  if not found then
    raise exception 'Mood record could not be found';
  end if;

  update public.attendance_wellbeing
  set mood = v_mood,
      updated_at = now()
  where visit_id = p_visit_id
  returning * into v_new;

  insert into public.attendance_audit (visit_id, action, old_record, new_record, changed_by)
  values (
    p_visit_id,
    'mood_updated',
    jsonb_build_object('wellbeing', to_jsonb(v_old), 'reason', btrim(p_reason)),
    jsonb_build_object('wellbeing', to_jsonb(v_new), 'reason', btrim(p_reason)),
    auth.uid()
  );
end;
$$;

create or replace function public.attendance_monthly_report(p_month_start date)
returns table (
  month_start date,
  month_end date,
  open_days bigint,
  days_with_sign_ins bigint,
  child_sign_ins bigint,
  unique_children bigint,
  community_sign_ins bigint,
  total_sign_ins bigint,
  avg_children_per_open_day numeric,
  avg_community_per_open_day numeric,
  good_moods bigint,
  okay_moods bigint,
  hard_day_moods bigint
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_start date;
  v_end date;
begin
  if not public.current_user_is_active_staff() then
    raise exception 'Active staff access required';
  end if;

  v_start := date_trunc('month', coalesce(p_month_start, current_date))::date;
  v_end := (v_start + interval '1 month - 1 day')::date;

  return query
  with active_visits as (
    select av.*
    from public.attendance_visits av
    where av.status = 'active'
      and av.service_date between v_start and v_end
  ),
  visit_counts as (
    select
      count(distinct service_date)::bigint as days_with_sign_ins,
      count(*) filter (where participant_type = 'child')::bigint as child_sign_ins,
      count(distinct child_id) filter (where participant_type = 'child')::bigint as unique_children,
      count(*) filter (where participant_type <> 'child')::bigint as community_sign_ins,
      count(*)::bigint as total_sign_ins
    from active_visits
  ),
  open_count as (
    select count(*)::bigint as open_days
    from public.operating_days od
    where od.is_open
      and od.service_date between v_start and v_end
  ),
  mood_counts as (
    select
      count(*) filter (where aw.mood = 'good')::bigint as good_moods,
      count(*) filter (where aw.mood = 'okay')::bigint as okay_moods,
      count(*) filter (where aw.mood = 'hard_day')::bigint as hard_day_moods
    from public.attendance_wellbeing aw
    join active_visits av on av.id = aw.visit_id
  )
  select
    v_start,
    v_end,
    oc.open_days,
    vc.days_with_sign_ins,
    vc.child_sign_ins,
    vc.unique_children,
    vc.community_sign_ins,
    vc.total_sign_ins,
    case when oc.open_days > 0 then round(vc.child_sign_ins::numeric / oc.open_days, 2) else null end,
    case when oc.open_days > 0 then round(vc.community_sign_ins::numeric / oc.open_days, 2) else null end,
    mc.good_moods,
    mc.okay_moods,
    mc.hard_day_moods
  from visit_counts vc
  cross join open_count oc
  cross join mood_counts mc;
end;
$$;

revoke execute on function public.sign_in_child(bigint, text, date, text) from public, anon;
revoke execute on function public.sign_in_visitor(text, text, text, date, text) from public, anon;
revoke execute on function public.sign_out_visitor(bigint) from public, anon;
revoke execute on function public.void_attendance_visit(bigint, text) from public, anon;
revoke execute on function public.correct_child_mood(bigint, text, text) from public, anon;
revoke execute on function public.attendance_monthly_report(date) from public, anon;

grant execute on function public.sign_in_child(bigint, text, date, text) to authenticated;
grant execute on function public.sign_in_visitor(text, text, text, date, text) to authenticated;
grant execute on function public.sign_out_visitor(bigint) to authenticated;
grant execute on function public.void_attendance_visit(bigint, text) to authenticated;
grant execute on function public.correct_child_mood(bigint, text, text) to authenticated;
grant execute on function public.attendance_monthly_report(date) to authenticated;;